### ISSUE TITLE
Связь с Cryptoki

### ISSUE THREAD

**Issue by agievich** [bcrypto/btok#10]
При описании личных ключей eSign обяснены правила настройки Cryptoki для работы с ними. Правила следующие:
1. Должны действовать соглашения СТБ 34.101.78.
2. Атрибут `CKA_ID` должен быть одним из 6 указанных выше идентификаторов.
3. Атрибут `CKA_SENSITIVE` должен принимать значение `CK_TRUE`, и это значение не может изменяться.
4. Атрибут `CKA_EXTRACTABLE` должен принимать значение `CK_FALSE`, и это значение не может изменяться.
5. При генерации ключей (механизм `CKM_EC_KEY_PAIR_GEN`) уровень стойкости, определяемый атрибутом `CKA_ID`, должен соответствовать параметрам ЭК, указываемым в атрибуте `CKA_EC_PARAMS` открытого ключа. Атрибуты `CKA_SIGN`, `CKA_UNWRAP` личного ключа и атрибуты `CKA_VERIFY`, `CKA_WRAP` открытого ключа должны принимать значение `CK_TRUE`.

Необходимо проверить корректность / полноту правил.

**Comment by semenov-vladyslav** [comment]
Добавил правило для атрибута `CKA_ALLOWED_MECHANISMS`:

Атрибут `CKA_ALLOWED_MECHANISMS` должен включать механизм `CKM_BIGN_TSP`,
а также механизм `CKM_BIGN_HBELT` при уровне стойкости `l=128` или
механизм `CKM_BIGN_BASH` при уровне стойкости `l=192` и `l=256`.
