### ISSUE TITLE
Размер сертификата КТ

### ISSUE THREAD

**Issue by olegotory** [bcrypto/btok#13]
При выполнении взаимной аутентфикации по протоколу BAUTH  криптографический токен (КТ) в сообщении М3 протокола передает терминалу через клиентскую программу (КП) свой сертификат. При этом сообщение М3 передается по защищенному сообщению, установленному между КТ и КП. Передача по защищенному соединению уменьшает максимальный размер полезных данных, возвращаемых командой, с 256 байтов до 243 = 256 - 13 байтов. Следовательно, сертификат  КТ не может быть больше 243 байтов. Оценим длину закодированного сертификата КТ для уровня стойкости l=128. 

Сертификат КТ -- это облегченный сертификат следующего формата:
CVCertificate ::= [APPLICATION 33] SEQUENCE {
  certificateBody ::= [APPLICATION 78] SEQUENCE {
   certProfileIdentifier           [APPLICATION 41] INTEGER { v1(0) },
   certAuthorityReference          [APPLICATION 2]  CharString,
   publicKey                       [APPLICATION 73] PubKey,
   certHolderReference             [APPLICATION 32] CharString,
   certHolderAuthorizationTemplate [APPLICATION 76] CertHAT OPTIONAL,
   certEffectiveDate               [APPLICATION 37] CVDate,
   certExpirationDate              [APPLICATION 36] CVDate,
   certExtensions                  [APPLICATION 5]  CVExt OPTIONAL 
  },
  signature [APPLICATION 55] OCTET STRING
}
Необязательные поля для сертфиката КТ не используются. При кодировании применяется правило T-L-V т.е. tag-length-value. При оценке будем предполагать, что для T и L используется по одному байту. Тогда получаем:
2 (T и L для CVCertificate) + 2 (T и L для certificateBody) + 3 (T, L и V для certProfileIdentifier) +
18 (T, L и V для certAuthorityReference) +  80 (T, L и V для publicKey) + 18 (T, L и V для certHolderReference) + 8 (T, L и V для certEffectiveDate) + 8 (T, L и V для certExpirationDate) + 
50 (T, L и V для signature) = 187 байтов.

Таким образом, для сертификата уровня стойкости l=128  есть запас 243 - 189 = 54 байтов, т.е. для 
получения сообщения протокола может использоваться "короткая" команда.  Для уровней стойкости l=192 и l= 256 размеры сертификатов увеличиваются на 56 и 112 байтов, т.е. для 
данных уровней стойкости при получении сообщения протокола должна использоваться "расширенная" команда.

**Comment by andrewkostevich** [comment]
Нужно пересчитать: для тэгов класса [APPLICATION ] со значением тэга больше 31 DER кодирование требует отводить два байта под тэг. Например, для IMPLICT [APPLICATION 41] INTEGER { v1(0) } DER представление будет 5F290100 - длина 4, а не 3. Для двух внешних SEQUENCE длина не влезет в один байт: под L будет отведено два байта.

**Comment by andrewkostevich** [comment]
В расчетах не учтен der(99, SW1||SW2): не хватает еще 4 байта

**Comment by agievich** [comment]
Сейчас, с учетом сокращения `CVCertCAZBYXXX -> CVCAZXXX`, какова длина сертификата? И укладывается ли он в одну команду на уровне l = 128?

**Comment by olegotory** [comment]
Сертификат КТ будет занимать максимум (в комментариях указываются длины для T-L или T-L-V или сразу макс. размер):

CVCertificate ::= [APPLICATION 33] SEQUENCE {                                        // 2 + 2 = 4
certificateBody ::= [APPLICATION 78] SEQUENCE {                                      // 2 + 2 = 4 
certProfileIdentifier [APPLICATION 41] INTEGER { v1(0) },                             // 2 + 1 + 1 = 4
certAuthorityReference [APPLICATION 2] CharString,                                     // 1 + 1 + 8 = 10
publicKey [APPLICATION 73] PubKey,                                                             // 82
certHolderReference [APPLICATION 32] CharString,                                      // 2 + 1 + 14 = 17
certHolderAuthorizationTemplate [APPLICATION 76] CertHAT OPTIONAL,   // 0 (для КТ не исп.)
certEffectiveDate [APPLICATION 37] CVDate,                                                //  2 + 1 + 6  = 9
certExpirationDate [APPLICATION 36] CVDate,                                              //  2 + 1 + 6 = 9
certExtensions [APPLICATION 5] CVExt OPTIONAL                                      // 0 (для КТ не исп.) 
},
signature [APPLICATION 55] OCTET STRING                                               // 2 + 1 + 48 = 51
}

Итого, размер сертифиата КТ = 4 + 4 + 4 +10 + 82 + 17 + 9 + 9 + 51 = 190 октетов.

Сертификат переадается по защищенному соединению при выполнении протокола bauth как der(82, M3), где M3 = <S_KT>_256 || Cert || T_KT. Размер M3 равен 32 + 190 + 8 = 130 октетов.

Значение der(82, M3) передается в ответе на команду, после установки защиты на RDF получим размер для RDF* = 1 + 2 + 1 + 130 + 1 + 1 + 8 = 244 байтов.
