### ISSUE TITLE
Согласованность между напечатанными и хранимыми данными ID карты

### ISSUE THREAD

**Issue by andrewkostevich** [bcrypto/btok#15]
На образцах ID-карт [https://citydog.by/post/zaden_pasport_id/](https://citydog.by/post/zaden_pasport_id/) указан номер ID-карты и личный номер **стандартного** формата, аналогичного паспорту. В стандарте номер ID-карты и личный номер имеют **нестандартный** формат: префиксы IDCBY- и PNOBY- соответственно перед значением. Важно ли, чтобы напечатанные и хранимые в электронном виде значения номера ID-карты и личного номера совпадали?

**Comment by alexshibkov** [comment]
Под номером КТА в соответствующей группе данных eID на idCard должен подразумеваться личный идентификационный номер гражданина, владельца idCard, который печатается.

**Comment by agievich** [comment]
1. Префиксы IDCBY, PNOBY наследуются из BPKI, а еще раньше -- из ETSI EN 319 412-1.
2. В контексте BPKI использование префиксов важно:
- разделяются типы идентификационных документов (IDC, PNO, PAS, потенциально можно еще  использовать TIN (УНН) и локальные страновые коды вида XX:);
- уточняются страны-эмитенты.
3. В контексте BTOK использование префиксов необременительно, не создается ненужная путаница.
4. То, что префиксы не печатаются на карте, не является проблемой. Более того, префиксы **и не следует** печатать. Ведь печать префикса это все равно что к номеру карты добавлять фразу: "не забывайте, это номер карты выданной в РБ". Зачем. И так понятно.

**Предлагаю**: сохранить префиксы.

**Comment by andrewkostevich** [comment]
После того, как терминал вычитает данные с ID-карты, передавать их прикладной информационной системе (личный номер и номер ID-карты) должен с префиксами или без? То есть прикладная информационная система должна знать про форматы личного номера гражданина или нет?

**Comment by agievich** [comment]
Прочитывается дата-группа. Она и передается. Т.е. с префиксами. Никакая другая логика в BTOK не вводится.

**Comment by agievich** [comment]
Без изменений. Но следует еще раз обдумать указание серийного номера в облегченных сертификатах (см. #23).
