### ISSUE TITLE
Жизненный цикл ID-карты

### ISSUE THREAD

**Issue by fynjy21** [bcrypto/btok#16]
Спецификация СТБ/ОР/34.101.79 не описывает жизненный цикл ID-карты согласно
Global Platform. Определены только APDU команды этапа жизненного цикла «SECURED»
согласно Global Platform, APDU команды других этапов жизненного цикла(«OP_READY»,
«INITIALIZED», «CARD_LOCKED», «TERMINATED») не определены. Описание APDU команд этапов жизненного цикла «OP_READY», «INITIALIZED» целесообразно оформить в виде стандарта предприятия, обеспечивающего производство карт.

**Comment by agievich** [comment]
СТБ 34.101.79 не может описать все аспекты инфраструктуры id-карт. Охват стандарта и так достаточно широк. Неохваченные вопросы должны отражаться в новых спецификациях, создаваемых по мере развития инфраструктуры. 

**Предложение**: без изменений.
