### ISSUE TITLE
Требования к КТА

### ISSUE THREAD

**Issue by fynjy21** [bcrypto/btok#17]
Спецификация СТБ/ОР/34.101.79 описывает требования к КТА без учета специфика платформ (персональный компьютер, защищенный микроконтроллер смарт- карты с JavaCard, защищенный микроконтроллер USB-токена) – в результате чего отдельные требования противоречат принципам защиты информации в операционной системе JavaCard. В частности, спецификация СТБ/ОР/34.101.79 предусматривает общие ресурсы прикладных программ eID и eSign: долговременные параметры (PIN/PUK/CAN коды), сеансовые данные (ключи защищенного соединения). Однако концепция операционной системы JavaCard предусматривает принадлежность ресурсов только одной прикладной программе и защиту ресурсов прикладной программы от других прикладных программ. Операционная система JavaCard предусматривает механизм взаимодействия между прикладными программами, который может использоваться для организации общего доступа к долговременным и сеансовым данным. Однако использование механизма взаимодействия создает риск несанкционированного доступа к разделяемым данным со стороны других установленных программ, поэтому установка других программ вместе с программами eID и eSign является нецелесообразной.

**Comment by olegotory** [comment]
Прикладные программы eID и eSign могут быть реализованы в виде одного Java-аплета.

**Comment by olegotory** [comment]
Стандарт не привязывается к конкретной платформе.
*Предложение*:  Ничего не менять.

**Comment by agievich** [comment]
Перенесено в #27.
