### ISSUE TITLE
Количество PIN

### ISSUE THREAD

**Issue by fynjy21** [bcrypto/btok#18]
Стандарт допускает совмещение функций неотказуемости (ЭЦП) и транспорта ключа для одной пары «личный-открытый ключ» программы eSign. Выполнение функций в базовом режиме авторизуется пользователем путем ввода одного и того же PIN, в результате пользователь не знает, какую операцию одобряет вводом PIN-кода. Целесообразно использовать разные PIN для разных операций.

**Comment by agievich** [comment]
Технически, сделать разные PIN для операций "Выработка ЭЦП" и "Расшифрование транспортируемого ключа" несложно. Но давайте вспомним, что есть еще PIN прикладной программы eID. Его тоже можно отделить от eSign/PIN. A еще в eSign поддерживается несколько личных ключей. Вплоть до 6. Итого, если быть последовательными (ведь мы же не знаем, какая операция сейчас выполняется), то нужно вводить 1 + 6 *2 = 13 различных PIN. Конечно, так нельзя.

Но вопрос поднят важный и мы действительно должны решить, сколько должно быть PIN. Диапазон: от 1 до 13.

**Comment by agievich** [comment]
1. Операции, выполненные в базовом режиме, по определению имеют более низкий статус безопасности, чем операции, выполненные в терминальном режиме. Статус операции (базовый/терминальный) можно понять по сертификату, связанному с личным ключом операции. В такой ситуации нет смысла выделять разные PIN для разных режимов. 

2. У нас априори есть доверие стороне, которая выполняет операции. В базовом режиме без этого доверия мы вообще ни о чем не можем говорить (мы видим только картинки и кнопки, генерируемые клиентской программой). В терминальном режиме доверие возникает в результате аутентификации терминала. Доверие есть, и мы можем не опасаться, что сторона, с которой мы работаем, будет жульничать с операциями.

**Предложение**: один PIN.

**Comment by andrewkostevich** [comment]
Компрометация PIN для ЭЦП несет угрозу для клиента в виде юридической ответственности за все документы с его ЭЦП. Компрометация PIN для аутентификации такой угрозы для клиента не несет.  Аутентификация может выполняться в публичных местах (интернет-кафе/киосках самообслуживания/банках): PIN  может быть подсмотрен окружающими и в случае одного PIN скомпрометирован будет доступ к функции выработки ЭЦП. 

Устоявшаяся практика для технологий идентификации и аутентификации:
 * технология Mobile ID (от всех международных поставщиков): два PIN - для аутентификации и для ЭЦП
 * немецкая ID-карта: два PIN - для аутентификации и для ЭЦП

Аналогия из банковской сферы: чиповая банковская карта требует PIN для любой оплаты, но в Австрии при покупке талонов в автомате, автомат снимает деньги не спрашивая PIN. Считается, что PIN от банковской карты может быть подсмотрен находящимися рядом людьми и в случае кражи карты с нее могут быть сняты деньги по PIN. А по банковской политике - снятие денег, подтвержденное PIN не может быть опротестовано. Поэтому для предотвращения краж карт, в опасных местах при платежах в специальных терминалах по карте просто не спрашивают PIN.

**Предложение**: два PIN.

**Comment by agievich** [comment]
Дискуссия свелась к развилке:
**A**. Единственный PIN, который обслуживает и eID, и eSign (Global PIN).
**B**. Операции eSign выводятся из под юрисдикции Global PIN. Перед их выполнением нужно ввести дополнительный Local PIN. 

Сейчас в BTOK реализован вариант **A**. Вариант **B** разумен, если операции eSign имеют более важное значение, чем операции eID. 

Но действительно ли это так? Спорный вопрос. Пройдя аутентификацию, я могу выполнять такие же критические действия, как если бы я подписывал документы. Пример: операции с карт-счетом после аутентификации через Интернет-банкинг. Более того, ввод Global PIN открывает доступ удаленному терминалу к чтению моих персональных данных и даже изменению некоторых из них. 

Не согласен, что повсеместно в Id-картах реализован вариант **B**. Например, в документе https://www.ssi.gouv.fr/uploads/2015/09/eidas_tr_signature_part1_v1_rc9-4.pdf действительно выделяются Global User Credentials (Global PIN, PUK, CAN)  и Local User Credentials (Local PIN). И при этом постоянно говорится о возможности отсутствия Local PIN, его поглощения Global PIN.

Если мы все-таки будем вводить вариант B, то следует продумать политику управления Local PIN:
1) блокировка / снятие блокировки;
2) смена (можно ли менять по PUK?);
3) описание прав управления в словах прав доступа eSign (и eID?).
Тонкостей будет довольно много, и ситуация сильно загромоздится.

**Comment by agievich** [comment]
Еще один аргумент против второго PIN  (назовем его PIN1), который обслуживает eSign.

Хорошо, мы не доверяем базовому PIN, опасаемся что он скомпрометирован, считаем что выработка ЭЦП гораздо более критическая операция чем аутентификация и требуем ввести PIN1 перед выработкой. 

Вопрос: как вводить PIN1? В открытом виде по защищенному соединению SM, построенном после BPACE[PIN]? Нельзя. Ведь мы считаем, что PIN скомпрометирован, следовательно весь трафик SM открыт противнику. Тогда нужно выполнять BPACE[PIN1] и строить новое соединение SM1 на его основе. 

Теоретически, нет проблем. Просто еще одно соединение. Но это уже третье, ведь есть еще SM0 -- соединение с терминалом. И даже с двумя соединениями было довольно трудно справиться. Третье соединение -- это существенное усложнение дизайна, а сложность, как мы знаем, -- это главный враг безопасности.

**Comment by agievich** [comment]
**Закрывается**. Предложение о вводе второго PIN недостаточно проработано.
