### ISSUE TITLE
Различия СОК для базового и терминального режимов

### ISSUE THREAD

**Issue by fynjy21** [bcrypto/btok#19]
Спецификация СТБ/ОР/34.101.79 не описывает различия сертификатов открытых ключей ЭЦП в случае базового и терминального режимов (согласно п. 6.5 «Сертификаты eSign являются стандартными»). В случае проверки ЭЦП проверяющая сторона не может определить режим – базовый или терминальный – в котором была сформирована ЭЦП и будет делать один и тот же вывод о подлинности ЭД. Целесообразно или оставить один сертификат, или разделить между сертификатами разрешенные операции с соответствующими личными ключами ЭЦП: например, один личный ключ – только для неотказуемости, второй личный ключ – для транспорта ключа и аутентификации

**Comment by agievich** [comment]
Сертификаты базового и терминального режимов отличаются. Отличия определены в СТБ 34.101.78 (см. идентификатор `bpki-eku-clientTM` в расширении `ExtKeyUsage`). 

В СТБ 34.101.79 сразу после пояснений, что сертификаты являются стандартными (т.е. не облегченными) четко сказано: "_Сертификаты должны соответствовать дополнительным 
требованиям, установленным в СТБ 34.101.78 для роли "Физические лица"._ 

**Предложение**: без изменений.
