### ISSUE TITLE
Команда для получения информации об апплете

### ISSUE THREAD

**Issue by fynjy21** [bcrypto/btok#20]
Целесообразно добавить APDU команду для получения информации об апплете (версия программного обеспечения, перечень доверенных сертификатов и т.п.) или закодировать данную информацию в коде ATR.

**Comment by agievich** [comment]
ATR -- это описание конкретный карты (КТ), а не архитектуры. В BTOK (архитектура) мы не можем задавать ATR, хотя, конечно, можем предложить шаблон описания. Но стоит ли это делать? Думаю, что нет. Мы вторгаемся на территорию инженерных вопросов.

ATR возвращается при подаче питания на карту, даже без запроса со стороны ридера. APDU-команда не нужна.

С другой стороны, информирование о возможностях карты является важной задачей, которую нужно будет решать в сопутствующих стандартах/спецификациях.

**Предложение**: без изменений.

**Comment by andrewkostevich** [comment]
Можно по аналогии c архитектурой eIDAS токена (https://www.bsi.bund.de/SharedDocs/Downloads/EN/BSI/Publications/TechGuidelines/TR03110/BSI_TR-03110_Part-3-V2_2.pdf?__blob=publicationFile&v=2):
 * файловая система включает файлы со сведениями о поддерживаемых протоколах и установленных корневых сертификатах в формате Certification Authority Reference (A.1.2). Поддерживаемые протоколы для нас не важны - так как они однозначно определяются версией стандарта, а список установленных корневых сертификатах вполне себе важная информация.
 * в ответ на APDU MSE:Set AT при инициализации PACE (B.1) при указании certHAT отдается информация о подходящих корневых сертификатах в формате Certification Authority Reference

Версию реализованной версии стандарта предлагается включить в AID апплетов в элемент PIX (см. предложение формата AIS в #22). Значение PIX можно также продублировать в historical bytes ATR для однозначной идентификации карты до начала работы прикладной программы с картой: по крайней мере прикладная программа сможет определиться с поддержкой таких идентификационных карт и запросить терминал о поддержке таких карт.

**Comment by agievich** [comment]
Нужны конкретные предложения, которые формулируются в самом начале. Иначе ничего не сойдется. По поводу ATR я уже высказался. Это конкретный почерк конкретной карты. Нет смысла стандартизации в BTOK. И еще. У нас не инженерный стандарт (по многим инженерным вопросам мы не имеем должной компетенции). И у нас не безразмерный стандарт, которые закрывает все вопросы инфраструктуры id-карт.

**Comment by agievich** [comment]
**Предложение**: дать конкретные предложения в виде отдельных issue, а эту тему закрыть.

**Comment by andrewkostevich** [comment]
Из #22: 

Для однозначной идентификации возможностей криптографической подсистемы просьба добавить в ASN.1 модуль переменную типа конфигурация-128, которая отражает согласованный набор поддерживаемых объектов: (bign-curve256v1, eID на первом уровне без необязательных групп данных, eSign на первом уровне).

`btok-configv1 OID ::= {btok-config 1}`

Базовые AIDы тоже продлить для отражения факта поддержки первого уровня или конфигурации: добавить в ASN.1 модуль
`id-eID-config1 OID ::= {id-eID 1}`
`id-eSign-config1 OID ::= {id-eSign 1}`
и объявить, что в  случае поддержки только уровня 1 будут такие AIDы

**Comment by agievich** [comment]
Перенесено в #49.
