### ISSUE TITLE
Режим APDU с расширенной длиной

### ISSUE THREAD

**Issue by fynjy21** [bcrypto/btok#21]
Для взаимодействия с ID–картой разрешено использовать режим APDU c расширенной длиной, однако данный режим:
        ◦ поддерживается  не всеми картридерами;
        ◦ не поддерживается реализацией NFC в мобильных устройствами на базе ОС Android.
Это существенно ограничивает выбор картридеров для персональных компьютеров и делает невозможным использование ID-карты на мобильных устройствах на базе ОС Android. Целесообразно отказаться от режима APDU c расширенной длиной, заменив команды, требующие данный режим, на цепочки APDU команд в стандартном режиме.

**Comment by olegotory** [comment]
Да, разрешено использовать режим APDU c расширенной длиной. Но сейчас для ключей на уровне стойкости l=128 можно обойтись без APDU c расширенной длиной.  Режим APDU c расширенной длиной больше на перспективу и в текущей id-карте может не поддерживаться.

*Предложение:* оставить без изменений.

**Comment by andrewkostevich** [comment]
> в текущей id-карте может не поддерживаться.

Предложение: явно написать, то что подразумевается: на уровне l=128 режим APDU с расширенной длиной не поддерживается.

**Comment by olegotory** [comment]
Считаю, что запрещать возможность использования на уровне l=128 режима APDU с расширенной длиной не стоит, так как есть разные карты.

**Предложение**:  написать, то что поддержка режима  APDU с расширенной длиной для уровня l=128 является необязательной.

**Comment by agievich** [comment]
В 12.1 добавлена фраза:
```
Поддержка расширенных форм Lc и Le не является обязательной в тех случаях, 
когда компоненты CDF и RDF не могут состоять из более чем 255 и 256 
октетов соответственно.
```

**Comment by andrewkostevich** [comment]
Часть данных (сертификат, Name, место рождения, орган выдавший карту) имеет длину больше 255 байт, из предложенной фразы следует **обязательность** поддержки расширенной формы APDU.

**Comment by olegotory** [comment]
Чтение и запист данных может выполняться любыми порциями (хоть по одному октету). Для них использование расширенных команд не является обязательным. Возможно фраза запутанная. Имелось в виду, что расширенные команды требуются для выполнения протокола bauth, если сообщения протокола не влезают в одну команду

**Comment by andrewkostevich** [comment]
Фраза трактуется однозначно: если терминал хочет вычитать сертификат и укажет Le=007FFF, то eSign должна вернуть данные одним блоком

**Comment by olegotory** [comment]
Не понял последний комментарий... Если используется расширенная длина ответа (из трех октетов), то понятно, что это расширенный формат команды.  Если мы не хотим использовать расширенные команды, то нужно использовать длины в коротком виде.

**Comment by andrewkostevich** [comment]
Не указано, что запись/чтение данных длиной более 255 (с учетом SecureMessaging, более 241) терминалом ДОЛЖНО выполняться в краткой форме и МОЖЕТ выполняться в РАСШИРЕННОЙ форме при наличии поддержки со стороны устройства взаимодействия с картой (карт-ридера)

**Comment by agievich** [comment]
**Предложение**. Переписать абзац:
>В тех случаях, когда можно обойтись короткими формами Lc и Le, поддержка расширенных форм не является обязательной.

**Comment by andrewkostevich** [comment]
Формулировка допускает различные толкования. 

> Обязательной является поддержка коротких форм Lc и Le, поддержка расширенных форм определяется возможностью их реализации в КТА и клиентской программе.

**Comment by agievich** [comment]
Предложенная формулировка не годится: могут быть случаи (объемные CDF/RDF при работе с CV-сертификатами второго и третьего уровней), когда короткие формы вообще нельзя использовать.

**Comment by andrewkostevich** [comment]
Тогда поддержку коротких форм сделать обязательной только для операций записи/чтения данных.

> Команды обновления/чтения данных должны использоваться с короткой формой Lc и Le и могут использоваться с расширенной формой в случае ее поддержки в КТА и клиентской программе

**Comment by agievich** [comment]
Предложенная формулировка неточна: 1) "КТА" -- нет такой аббревиатуры, 2) не упомянут терминал, 3) команды чтения/записи еще не введены в контекст. И совершенно непонятно, что не устраивает в формулировке, предложенной нами.

**Comment by andrewkostevich** [comment]
Команд чтения/записи отправляет терминал, соответственно значения Lc, Le выбирает терминал. Предложенная формулировка не обязывает терминал использовать короткую форму, соответственно это ведет к несовместимости в случае если КТА и/или клиентская программа не поддерживают расширенную форму Le, Lc.

**Comment by agievich** [comment]
Ясно. Тогда предлагается вот так:

> В тех случаях, когда можно обойтись короткими формами Lc и Le, поддержка расширенных форм со стороны КТ не является обязательной. КП и терминал должны учитывать данное правило при выборе форм команд в процессе взаимодействия с токеном.

**Comment by andrewkostevich** [comment]
Чтобы разработчику терминала/КП было понятно, дополнительно к предлагаемой фразе, в описании команды обновления лучше явно указать: 

> Должна использоваться короткая форма Lc, расширенная форма может использоваться в случае ее поддержки в КТ и КП

Чтобы разработчику терминала/КП было понятно, дополнительно к предлагаемой фразе, в описании команды чтения лучше явно указать: 

> Должна использоваться короткая форма Le, расширенная форма может использоваться в случае ее поддержки в КТ и КП

**Comment by olegotory** [comment]
Считаю, что предложенная @andrewkostevich  формулировка
> расширенная форма может использоваться в случае ее поддержки в КТ и КП

некорректна: при разработке карты неизвестно, будут ли поддерживать КТ и КП расширенные формы.

**Comment by andrewkostevich** [comment]
Не знаю, о какой интерпретации фразы 

> расширенная форма может использоваться в случае ее поддержки в КТ и КП

говорит @olegotory, но имеется в виду, что терминал априорно не знает, поддерживает ли КТ и КП расширенные формы Lc и Le, поэтому терминал должен использовать краткую форму, но ему не запрещено использовать  расширенную форму если у терминала имеется информация, что расширенная форма поддерживается и КТ и КП

**Comment by agievich** [comment]
Я также считаю, что предложенные дополнения к описаниям команд чтения/обновления неточны. К какой стороне относится фраза "Должна использоваться"?  Логично предположить, что ко всем.  Но тогда продолжение ("может использоваться") вступает в противоречие с этой фразой. Непонятно, почему КП ставится в один ряд с КТ. КП находится в таком же зависимом от КТ положении при выборе форм команд.

В любом случае дополнительные объяснения при описании команд чтения/обновления избыточны.

Принимается в редакции:

>В тех случаях, когда можно обойтись короткими формами Lc и Le, поддержка расширенных форм со стороны КТ не является обязательной. КП и терминал должны учитывать это при выборе форм команд в процессе взаимодействия с токеном.
