### ISSUE TITLE
Идентификаторы eID и eSign

### ISSUE THREAD

**Issue by fynjy21** [bcrypto/btok#22]
Выбор идентификаторов прикладных программ eID и eSign противоречит требованиям ISO 7816-5: использование диапазона E, принадлежащего ISO, возможно после регистрации идентификаторов в ISO. Префикс E8 в id-eID в приложении Б противоречит ASN.1 модулю, в котором
 id-eID ::= OBJECT IDENTIFIER {btok-apps1}.

**Comment by agievich** [comment]
Не могу сказать, что глубоко вникал в вопрос. Позволю сделать некоторые комментарии, которые могут упорядочить дискуссию.

AID представляют собой объединение RID (Registered application provider IDentifier, 5 байтов) и RIX (Proprietary application Identifier eXtension, <= 11 байтов). Разумной (и лаконичной) видится схема с 3-байтовыми RIX: 2 байта для номера прикладной программы, 1 байт для номера версии. Итого, 8-байтовые AID.

Есть два пути выбора AID: длинный и короткий.

*Длинный путь: глобальная видимость*. Для глобального распознавания и RID, и AID (?) нужно регистрировать. Вот здесь можно найти реестры: https://www.eftlab.co.uk/index.php/site-map/knowledge-base. Интересно, что в реестре AID нет многих известных решений, связанных с национальными id-картами. Как видим, глобальная видимость для них не так уж и важна.

*Короткий путь: локальная видимость*.  Если RID (т.е. AID) начинается с `F`, то идет речь о проприетарном (локальном) идентификаторе. Его не надо регистрировать. Стоит ли нам использовать такие AID? Не знаю.

Сейчас в BTOK сделано так. В АСН.1-модуле введены 12-байтовые OID для eID, eSign. AID получаются из этих OID добавлением префикса `E8` (не начинается с `F`). Нужно уточнить такую логику. Возможно речь шла о том, что глобальная видимость не важна, и поэтому схемой AID = RID + RIX можно пренебречь.

**Comment by andrewkostevich** [comment]
Согласно ISO/IEC 7816-5: 

5.2.3 Registration category = ‘D’
 * Registration category : 4 bits, coded as 1101
 * Country code of the national registration authority,  12 bits as 3 BCD digits, coded according to IS0 3166, numeric part only
 * Field(s) specified by the national authority, 24 bits, BCD coding recommended.
 * Proprietary AID estension: up to 11 bytes

Итого 
 * RID: `D1 12 XX XX XX`, например `D1 12 02 00 00`
 * PIX eID: `34 10 17 91 71 XX XX XX XX XX XX` где `XXXXXXXXXXXX` опциональная информация - версия профиля eID
 * PIX eSign: `34 10 17 91 72 XX XX XX XX XX XX` где `XXXXXXXXXXXX` опциональная информация - версич профиля eSign
 * AID eID: `D1 12 02 00 00 34 10 17 91 71` 
 * AID eSign: `D1 12 02 00 00 34 10 17 91 72`

**Comment by agievich** [comment]
В целом поддерживаю. Но предлагаю быть ближе к идентификаторам id-eID, id-eSign, введенным в приложении к BTOK. Напомню, что они вводятся по схеме СТБ 34.101.50, разумно этой схемы придерживаться. 

RID = `D1 12 00 02 00` (`D1 12` -- by, объяснено выше; `00` -- standard; `02` -- std; `00` -- stb);
RIX_eID = `22 65 4F 07 01` (`22` = 34, `65` = 101; `4F` = 79; `07` = apps; `01` = eiD)
RIX_eSign = `22 65 4F 07 02` (`22` = 34; `65` = 101; `4F` = 79; `07` = apps; `02` = eSign)

Итого
AID_eID = `D1 12 00 02 00 22 65 4F 07 01`
AID_eSign = `D1 12 00 02 00 22 65 4F 07 02`

При определении AID сказать, что они построены по DER-кодам объектных идентификаторов заменой префиксов.

**Comment by andrewkostevich** [comment]
В AID лучше вставить  версию стандарта - `01` - как вариант, между `4F` и `07`. Иначе если/когда стандарт будет обновлен - можно будет определить версию протоколов, поддерживаемые APDU.

**Comment by agievich** [comment]
Давайте придерживаться стандартной схемы. Если в новой редакции стандарта появляются новые объекты, то им присваиваются незанятые номера.

**Comment by agievich** [comment]
Корректировка AID отражена в #45

**Comment by andrewkostevich** [comment]
Для однозначной идентификации возможностей криптографической подсистемы просьба добавить в ASN.1 модуль переменную типа конфигурация-128, которая отражает согласованный набор поддерживаемых объектов: bign-curve256v1, eID на первом уровне без необязательных групп данных, eSign на первом уровне. 

`btok-configv1 OID ::= {btok 128}`

**Comment by agievich** [comment]
Реакция отражена в #45.
