### ISSUE TITLE
Поле certHolderReference

### ISSUE THREAD

**Issue by fynjy21** [bcrypto/btok#23]
Поле certHolderReference в сертификате является номером – целесообразно отказаться от вариативности длины и зафиксировать формат номера постоянной длины (по аналогии сcertAuthorityReference).

**Comment by andrewkostevich** [comment]
В ISO 7816-8 указано про формат CV сертификата: должен включать "5F20 — L — Имя держателя карты". В ISO 7816-6 указано: формат значения "Имя держателя карты" для тэга 5F20 - numeric 2...26. Поэтому, в частности, префикс 'BY' недопустим по ISO 7816-6. Аналогичное несоответствие будет и для Certification Authority Reference: по ISO 7816-4 у него совсем другой формат. Предлагаемый формат 'BYXXXXX' заимствован из требований к eIDAS: BSI TR-03110-3 Advanced Security Mechanisms for Machine Readable Travel Documents – Part 3. Их мотивация выбора такого формата номера  понятна: им важен код страны - так как eIDAS действует для всех стран Евросоюза, они вынуждены использовать вариативный номер внутри страны - регулировать форматы номеров внутри каждой страны по понятным причинам они не могут и поэтому не хотят. У нас другая ситуация и другая мотивация - спецификация распространяется только на одну страну - нашу, поэтому префикс 'BY' не несет никакой информации, формат номера мы можем выбрать сами как хотим. Предлагается - зафиксировать формат номера постоянной длины  (чтобы сертификат влазил в одну APDU #13).

**Comment by agievich** [comment]
Если идет речь о сокращении длины сертификата, то лучше переключиться на `certAuthorityReference`. Имена здесь имеют формат `BYCVCertCAZBYXXX`, их вполне можно сокращать. Например, можно убрать второе вхождение `BY`. Что касается префикса `BY` в `certHolderReference`, то не вижу ничего плохого в следовании традиции eIDAS.

**Q**. Насколько нужно сократить длину сертификата?

**Comment by andrewkostevich** [comment]
Кроме сокращения длины, формулировка "Если же субъектом является КТ или терминал, то идентификационная строка должна быть получена добавлением к серийному номеру субъекта префикса ’BY’. Например, ’BY590082394654’. Длина серийного номера не должна превышать 14 символов" допускает трактование, что длина идентификационной строки составляет 16 символов. 

Максимальная общая длина сертификата: #13

**Comment by agievich** [comment]
**Предложение**:
1. Сократить имена УЦ в `certAuthorityReference`: `BYCVCertCAZBYXXX` -> `BYCAZXXX` (на 8 символов).
2. "Длина серийного номера не должна превышать 14 символов" -> "Длина серийного номера не должна превышать 12 символов".
3. Изменить тип `CharString` на `OCTET STRING (SIZE (8..14))`.
4. Объяснить, как символы имен представляются октетами `CharString`. Сослаться на таблицу КОИ-7 из ГОСТ 27463 (в стиле СТБ 34.101.47).

**Comment by andrewkostevich** [comment]
Лучше не вводить вариативность длины номера, так как это не дает дополнительных возможностей для пользователей, а только усложняет парсинг: лучше сразу зафиксировать максимальную длину 14: `OCTET STRING (SIZE (14))`

**Comment by agievich** [comment]
Но мы же боремся за сокращение длины сертификата... Разве помешают лишние 6 октетов? Или даже 12, если речь идет о промежуточном сертификате.

**Comment by agievich** [comment]
``Длина серийного номера не должна превышать 12 символов``. 
Но тогда надо вводить и ограничение снизу: не меньше 6.  
Или все-таки потребовать, чтобы серийный номер состоял строго из 12 символов?

**Comment by agievich** [comment]
Обсуждение переносится в #45
