### ISSUE TITLE
Функция разбора токена ключа

### ISSUE THREAD

**Issue by fynjy21** [bcrypto/btok#24]
Расшифрованный ключ из токена может быть отправлен только на терминал. В результате терминал должен или иметь функцию по дальнейшей передаче расшифрованного ключа или являться СКЗИ и выполнять расшифрование данных. Если терминалом является сервер аутентификации — сервер имеет доступ к ключу шифрования и расшифрованным данным и пользователь вынужден мириться с нахождением его расшифрованных данных на сервере.

**Comment by agievich** [comment]
Да, терминал может и расшифровывать, и подписывать. Именно такое поведение мы и подразумевали.

Пример: терминал обслуживает облачный сервер, участвуя в сервисах "Облачная ЭЦП", "Облачное хранение". 

**Предложение**: без изменений.

**Comment by andrewkostevich** [comment]
Может ли расшифрованный ключ быть передан терминалом в клиентскую программу?

**Comment by agievich** [comment]
Формально, да. Терминал может передавать КП все что угодно. В том числе ключи.

**Comment by andrewkostevich** [comment]
В общем случае (для расшифрования локальынх сообщений), терминал ДОЛЖЕН передавать КП расшифрованный ключ. 

TODO: в спецификации терминала должен быть разработан механизм передачи ключа в КП

**Comment by olegotory** [comment]
В спецификации есть механизм передачи расшифрованных данных сразу в клиентскую программу (без участия терминала). Если передать расшифрованные данные необходимо в клиентскую программу, то можно работать вообще без терминала, т.е. использовать для зашифрования/расшифрования ключ специально предназначенный для этого (ключ для состояния PS), при этом расшифрованные данные будут переданы по защищенному соединению "КП -- КТ".

**Comment by andrewkostevich** [comment]
> Если передать расшифрованные данные необходимо в клиентскую программу, то можно работать вообще без терминала, т.е. использовать для зашифрования/расшифрования ключ специально предназначенный для этого (ключ для состояния PS)
Ключ выбирает отправитель, не владелец ключа: он может выбрать ключ для состояния AS

**Comment by olegotory** [comment]
Для расшифрования используется стандартная apdu-команда, на вход которой подаеются зашифрованные данные, а в ответ возвращаются расшифрованные. Кто вызыват команду (терминал или клиентская программа), тот и получает расшифрованные данные. Какой здесь можно придумать механизм? Сохранять данные в карте в каком-то файле, а потом читать с помощью клиентской программы? Считем нецелесообразным такой механизм, от нестандартный и небезопасный.

**Comment by olegotory** [comment]
Стандарт описывает только взаимодействие "КП - КТ" и "терминал - КТ". Взаимодействие "КП - терминал" в стандарте не описывается, так как не являлось задачей стандарта.

**Comment by andrewkostevich** [comment]
> Для расшифрования используется стандартная apdu-команда, на вход которой подаеются зашифрованные данные, а в ответ возвращаются расшифрованные. 

В стандарте есть только apdu-команда для разбора токена ключа, которая расшифрует ключ шифрования данных, этот ключ далее как-то должен попасть в клиентскую программу, которая локально будет расшифровывать данные. 

> Кто вызыват команду (терминал или клиентская программа), тот и получает расшифрованные данные. 

apdu-команды для расшифрования данных в стандарте нет.

> Какой здесь можно придумать механизм? Сохранять данные в карте в каком-то файле, а потом читать с помощью клиентской программы? Считем нецелесообразным такой механизм, от нестандартный и небезопасный.

Про это и тикет: в терминальном режиме функция транспорта ключа выглядит сомнительно

**Comment by olegotory** [comment]
Я имел в виду команду разбора токена.

Почему сомнительно. А если у меня облачное хранение зашифрованных данных. Сервер расшифровывает только то, что мне нужно и отображает. Разные данные при этом зашифрованы на разных ключах. При хранении данных обеспечивается защита, при этом если данные с сервера и украдут, то не расшифруют. Можно наверное и другие сценарии придумать.

**Comment by andrewkostevich** [comment]
> А если у меня облачное хранение зашифрованных данных. Сервер расшифровывает только то, что мне нужно и отображает.

Возвращаемся к TODO: в спецификации терминала должен быть разработан механизм передачи ключа в КП/сервер облачного хранения. 

Это касается не этого стандарта, а спецификации терминала - надо думать такая спецификация будет - в спецификации терминала должен быть предусмотрен такой механизм, иначе смысла транспорта ключа в терминальном режиме нет.

**Comment by agievich** [comment]
"Терминал ДОЛЖЕН передавать КП расшифрованный ключ". "Иначе смысла транспорта ключа в терминальном режиме нет". Почему? Ведь в самом начале я привел пример: хранение данных в облаке. Мне отправляют данные в облако, зашифровывая на моем открытом ключе. Я расшифровываю данные с помощью терминала и получаю их. Получаю данные, а не ключ. Возможны другие сценарии. Разве мы должны их специфицировать в BTOK? Ведь стандарт устанавливает всего лишь **криптографическую архитектуру КТ**.

**Comment by agievich** [comment]
**Предложение** (повторно): без изменений.
