### ISSUE TITLE
Уровень выполнения APDU

### ISSUE THREAD

**Issue by fynjy21** [bcrypto/btok#25]
Спецификация вводит понятие «Уровень выполнения APDU» (таблица 8 Операции КТ): в случае 
ID-карты на базе JavaCard значения «все» и «MF» недопустимы, должна быть указана конкретная прикладная программа-обработчик. Для команды выбора прикладной программы допустимо значение «операционная система».

**Comment by agievich** [comment]
Правила BTOK соответствуют ISO/IEC 7816-15. Сделано по аналогии с правилами eIDAS (https://www.ssi.gouv.fr/uploads/2015/09/eidas_tr_signature_part1_v1_rc9-4.pdf, стр. 70).

В BTOK мы не привязываемся к JavaCard. Целесообразность привязки является дискуссионной.

Пока в таблицу 8 вносится редакционные изменения: "любой" вместо "все".

**Comment by olegotory** [comment]
У нас нет привязки к конкретной платформе.
Структура файловой системы и возможные способы выбора файлов соответствует международным аналогам (например, EIDAS).

**Предложение**: ничего не менять.

**Comment by agievich** [comment]
Вопрос перенесен в #27.
