### ISSUE TITLE
BigEndian vs LittleEndian

### ISSUE THREAD

**Issue by fynjy21** [bcrypto/btok#26]
Криптоакселераторы смарт-карт возвращают данные в формате BigEndian, после выбора защищенного микроконтроллера целесообразно изменить в спецификации СТБ/ОР/34.101.79 формат на BigEndian чтобы избежать накладных расходов по изменению формата.

**Comment by agievich** [comment]
BigEndian противоречит сложившейся в наших стандартах практике. Хорошо, мы изменим BAUTH, переведем на BigEndian представление точек ЭК. Но что делать с уже стандартизированным BPACE? И как не запутаться в перключениях BigEndian / LittleEndian. Ведь криптография вокруг Belt тяготеет к LittleEndian.

В конце концов, расходы на разворот октетов не столь существенны.

**Предложение**: без изменений.
