### ISSUE TITLE
Команда выбора прикладной программы

### ISSUE THREAD

**Issue by fynjy21** [bcrypto/btok#27]
Команда выбора прикладной программы по защищенному соединению выполнена быть не может, так как за выбор программы отвечает операционная система JavaCard, а защищенное соединение не может быть установлено на уровне операционной системы. Следует определить способ реализации защищенного соединения с учетом требований операционной системы JavaCard: на уровне ОС (возможно только в кастомизированных ОС), в каждой прикладной программе (проблема разделения библиотеки криптографических функций между программами), через взаимодействие между прикладными программами с реализацией защищенного соединения в служебной прикладной программе (реализовано в макете).

**Comment by olegotory** [comment]
У нас нет привязки к конкретной платформе. 
Набор команд стандарта и возможные способы их вызова соответствует международным аналогам (например, EIDAS).

**Предложение**: ничего не менять.

**Comment by agievich** [comment]
Разрешение на выбор прикладной программы с помощью открытой (вне рамок защищенного соединения) команды можно реализовать следующим образом:

1. В раздел 11 добавляется абзац:
```
В состояниях PS и AS все команды и соответствующие ответы должны передаваться 
в рамках активного защищенного соединения. Исключение составляет команда выбора 
прикладной программы (см. 12.2.4), которая может передаваться 
в открытом виде, т.~е. вне рамок защищенного соединения. При этом обеспечивается 
возможность переключения между изолированными (на уровне операционной 
системы КТ) прикладными программами.
```
2. В п. 12.4.5 предложение "команда передана в открытом виде" продолжается фразой
```(за исключением команды выбора прикладной программы, см. 12.2.4);```

Описанные корректировки опасны. **Их следует еще раз обсудить.** Противник может навязать КТ переход на другую прикладную программу, и не подозревающий о переходе терминал будет получать ложные ошибки выбора файлов или, если eID и eSign подчинены файлы с одинаковыми FID (сейчас такого нет), будет читать совершенно другие данные.

Снова **предлагается** сохранить действующую логику. На уровне JavaCard (если он используется) eID и eSign интерпретируются как единый апплет. Апплет получает команды по защищенному соединению, внутри апплета выполняется переключение между прикладными программами (фактически, подпрограммами апплета).
