### ISSUE TITLE
Алгоритм защищенного соединения

### ISSUE THREAD

**Issue by fynjy21** [bcrypto/btok#28]
Алгоритм защищенного соединения не позволяет обрабатывать APDU команду с одним буфером за один вызов (поле Lc исключено из вычисления MAC): расходование памяти или на выделение контекста выработки MAC и несколько вызовов или выделение буфера и накладные расходы на копирование. Рекомендуется уточнить алгоритм защищенного соединения (например, заменять поле Lc заполнителем 00).

**Comment by olegotory** [comment]
Длина Lc может быть 0, 1 или 3 октета (в коротком и расширенном виде). Если поле присутствует, то оно учитывается при вычислении mac. Если поле отсутствует и заменить его заполнителем, то нужно вводить два алгоритма: для коротких и расширенных команд.
Отмечу, что алгоритм защищенного соединения, приведенный в стандарте, максимально приближен к стандартному (в нашем случае не используется дополнение). В стандартном алгоритме не производится заполнения Le нулями.
Для команд в коротком виде требуется буфер длины 4 + 1 + 255 +1 байтов. При этом накладные расходы по выделению памяти и копированию при отсутствию поля Le будут незначительными.
Для команд в расширенном виде придется и так имитовставку вычислять порциями.
Предлагается оставить как есть.
