### ISSUE TITLE
Формат защищенного соединения

### ISSUE THREAD

**Issue by fynjy21** [bcrypto/btok#29]
Формат защищенного соединения целесообразно описать для каждого типа APDU- команды 
(типы 1-4), так как не понятна обязательность защиты поля Le, которое обычно не задается и для него используется значение по умолчанию 00, которое заменяется на значение 255.

**Comment by olegotory** [comment]
В п. 12.4 лучше наверное заменить «Если Le > 0» на «Если команда содержит Le …»

**Comment by agievich** [comment]
Включено в #36.
