### ISSUE TITLE
Уточнить, как передавать сертификат при выполнении команды проверки сертификата

### ISSUE THREAD

**Issue by olegotory** [bcrypto/btok#3]
При описании команды проверки сертификата следует уточнить, как передавать стандартный сертификат без использования расширенного поля данных (т.е. при использовании поля данных, размер которого не превышает 255 байт). Следует сказать, что в этом случае для сертификата, размер которого превышает 255 байт, должна использоваться цепочка команд, в которой передаются последовательные части сертификата. При этом, если необходимо передать последовательно несколько сертификатов, то для каждого сертификата должна использоваться своя цепочка.
Также следует уточнить, что для передачи облегченного сертификата по частям должна использоваться цепочка команд.

**Comment by agievich** [comment]
Стандартный сертификат не передается. См. также #34.
