### ISSUE TITLE
Модификация протокола BPACE

### ISSUE THREAD

**Issue by fynjy21** [bcrypto/btok#30]
Исходя из набора команд криптоакселераторов защищенных микроконтроллеров, целесообразно оценить возможность модификации протокола BPACE: для вычисления случайной точки W вместо операций с большими числами использовать операцию вычисления кратной точки.

**Comment by agievich** [comment]
Протокол BPACE основан на идее Яблона: по паролю (слабому секрету) сгенерировать секретную точку W и запустить на этой точке протокол Диффи -- Хеллмана. 

В BPACE для генерации W используется хэширование в группу точек ЭК. Да, при хэшировании используется АБЧ. Причем на обычных вычислительных платформах хэширование существенно проще, чем вычисление кратной точки ЭК.

Известна альтернатива: генерировать W в рамках обычного протокола Диффи -- Хеллмана. Тогда можно отказаться от АБЧ в пользу арифметики ЭК. Но переход на новый способ генерации W потребует дополнительной пересылки ключей Диффи -- Хеллмана. Представляется, что эта пересылка будет стоить дороже, чем текущие вычисления.

Кроме этого, потребуется стандартизация ответвления BPACE, что не очень здорово.

**Предложение**: без изменений.
