### ISSUE TITLE
Управляющие части APDU команды

### ISSUE THREAD

**Issue by fynjy21** [bcrypto/btok#31]
Управляющие части APDU команды (P1P2) инициализации протоколов BPACE и BAUTH совпадают и выбор протокола осуществляется в зависимости от контекста и параметров команды. Рекомендуется использовать разные управляющие части APDUкоманды.

**Comment by olegotory** [comment]
Предлагается поменять значения P1||P2 команды инициализации протокола BAUTH на следующие значения (см. ISO 7816-4, таблица 78): 
F1A4 для взаимной аутентификации;
B1A4 для односторонней аутентификации (см. ISO 7816-4, таблица 78).
Для P1||P2 команды инициализации протокола BPACE остается значение C1A4.

**Comment by agievich** [comment]
Отражено в #45.
