### ISSUE TITLE
Набор DER структур

### ISSUE THREAD

**Issue by fynjy21** [bcrypto/btok#32]
APDU команда инициализации BPACE в качестве параметра содержит набор DER структур с тэгами разных форматов (длиной 1 и 2 байта). Для оптимизации обработки целесообразно использовать тэги одного формата (длиной 1 байт – если имеются незанятые тэги длины 1).

**Comment by olegotory** [comment]
Для тэгов длины 2 используются стандартные тэги, определенные в ISO 7816.
Использование нестандартных тэгов считаем нецелесообразным.
