### ISSUE TITLE
Передача сертификата в КТ

### ISSUE THREAD

**Issue by fynjy21** [bcrypto/btok#34]
Размер сертификата терминала не позволяет передать сертификат в КТ по защищенному соединению за одну команду: в спецификации предусмотрен опциональный режим цепочки команд. Целесообразно режим цепочки команд сделать обязательным (реализовано в макете).

**Comment by olegotory** [comment]
В спецификации для команды <PSO: Verify Certificate> (см. п. 12.2.21) сказано:
" В компоненте CDF команды передаются тело и подпись облегченного сертификата.
Для их передачи может использоваться цепочка из двух команд <PSO: Verify Certificate>,
первая из которых содержит тело облегченного сертификата, а вторая — подпись облег-
ченного сертификата.
Для передачи нескольких сертификатов, составляющих маршрут сертификации, дол-
жен использоваться последовательный вызов команд <PSO: Verify Certificate>. При этом если какой-либо сертификат передается цепочкой команд, то для него должна использо-
ваться своя цепочка."
Здесь имеется в виду, что сертификат может быть передан за одну команду или как цепочка двух команд, т.е передача сертификата за две команды не является опцианальной. Возможно нужно написать более строго ....

**Comment by andrewkostevich** [comment]
Аналогично #13, нужно пересчитать размер сертификата терминала. Если он оказывается больше 256 байт, то сертификат не может быть передан за одну команду и режим цепочки становится обязательным.

**Comment by olegotory** [comment]
Нужно определиться с длинами имен в сертификатах, тогда можно будет посчитать для всех возможных типов сертификатов терминала. Возможно на перспективу целесообразно поддержать два способа передачи сертификата.

**Comment by agievich** [comment]
На уровне l = 128 мы укладываемся в одну команду (см. #13 , #23, #45). Но есть же еще сертификаты уровней l = 192, 256 (по крайней мере, потенциально). Согласен, что описание в п. 12.2.21 следует усилить, объяснив две возможности передачи сертификатов.

**Comment by andrewkostevich** [comment]
На уровне 128 сертификат может быть отправлен в одну команду, в описании нужно указать, что должен использоваться способ с минимальным число команд, потому как реализовывать два варианта отправки не целесообразно.

**Comment by olegotory** [comment]
Размер сертификата терминала по сравнению с сертификатам КТ (см. #13)  может максимум дополнительно содержать компоненты:
   certHolderAuthorizationTemplate [APPLICATION 76] CertHAT OPTIONAL, // 22 октета
   certExtensions [APPLICATION 5] CVExt OPTIONAL  // 1 + 1 + 1 + 1 + 10 + 19 = 33 октета
Учитывая длину сертификата КТ и то, что при проверке сертификата передается не сертификат целиком (фактически первые 4 байта отбрасываются), получим, что в команду в качестве RDF  может быть передано 190 - 4 + 22 + 33 = 241 октет. 
Защищенное соединение добавляет 1 + 2 + 1 + 1 + 1 + 8 = 14 октета.
Итого получаем, что RDF* будет иметь размер 255 октета, т.е. влезает в одну команду без использования расширенного режима.

**Comment by olegotory** [comment]
Сертификаты УЦ (корневого и промежуточных) будут меньше сертификата КТ на 6 октета, т.е. длина CDF* при их проверке будет 251 октет.

**Comment by olegotory** [comment]
Открыто, так как требуется уменьшить длину сертификата терминала

**Comment by agievich** [comment]
В `certHolderReference` сертификатов КТ и термнала исключен префикс `BY`. Длины сертификатов сокращены на 2 октета. Теперь сертификат терминала помещается в одну команду на уровне l = 128. Изменения отражены в #45.

**Comment by olegotory** [comment]
В папку model\certs добавлены модельные сертификаты для корневого УЦ, подчиненного УЦ, терминала и КТ
