### ISSUE TITLE
Отправка сообщения М3

### ISSUE THREAD

**Issue by fynjy21** [bcrypto/btok#35]
Размер сертификата КТА не позволяет переслать сообщение M3 в одной APDU команде: для отказа от расширенной длины APDU отправку M3 целесообразно разбить на две команды (реализовано в макете).

**Comment by olegotory** [comment]
Размер сертификата КТ будет уменьшен до размера, позволяющего передать сертификат в ответе на команду (в виде сообщения M3) без использования расширенной длины APDU

**Comment by agievich** [comment]
Если сокращение размера сертификата на 6-12 символов достаточно (см. #23, #45), то давайте закрывать этот вопрос.
