### ISSUE TITLE
Команда переключения ключевого набора

### ISSUE THREAD

**Issue by fynjy21** [bcrypto/btok#36]
В команде переключения ключевого набора не указано, на каком ключевом наборе защищать ответ.

**Comment by agievich** [comment]
Требуются пояснения. Непонятно, о каком переключении идет речь. Может быть о переключении между защищенными соединениями?

**Comment by andrewkostevich** [comment]
Переключение между защищенными соединениями: выполняется переход на другие ключи защищенного соединения. Непонятно какими ключами пользоваться для защиты ответа этой команды: старыми, на которых была отправлена команда, или новыми, на которые выполнено переключение

**Comment by olegotory** [comment]
Кто послал команду, тот и должен получить ответ. Следовательно для шифрования команды и ответа используется один и тот же ключевой набор (т.е. команда и ответ пересылаются по одному защищенному соединению).

**Comment by olegotory** [comment]
**Предложение**: оставить как есть, так как понятно, что тот, кто отправил команду, тот и должен получить ответ.

**Comment by agievich** [comment]
**Предложение**: переписать описание защиты команд и ответов в п. 12.4. Сделать его более понятным, возможно сопроводить рисунком. В том числе учесть замечание #29. В том числе прокомментировать, что ответ защищается в том же соединении, в котором была отправлена  команда.

**Comment by agievich** [comment]
Отражено в  #44 .
