### ISSUE TITLE
Требования к объектам eID

### ISSUE THREAD

**Issue by fynjy21** [bcrypto/btok#37]
Спецификация СТБ/ОР/34.101.79 ссылается на инфраструктуру для выпуска открытых ключей аутентификации ID-карты и терминалов, инфраструктуру терминалов, но не выдвигает требований к данным инфраструктурам. Разработка ID-карты в общем случае (не зафиксированное число корневых сертификатов и сертификатов подчиненных УЦ, наличие цепочек сертификатов) требует больше ресурсов микроконтроллера для программ и хранения данных, снижает быстродействие 
ID-карты. Например, увязывание сроков действия сертификатов инфраструктур со сроком действия ID-карты упрощает установление доверия к сертификатам терминалов, может исключить необходимость в цепочках сертификатов.

**Comment by agievich** [comment]
Сразу несколько замечаний / предложений. Попытаюсь реконструировать. Но прежде еще раз повторю, что BTOK не касается вопросов инфраструктуры. Область действия: криптографическая архитектура КТ.

1. Да, разрешается хранить в КТ "один или несколько" корневых сертификатов. Разные сертификаты могут потребоваться на разных уровнях стойкости. Конечно, опция "один корневой сертификат" является предпочтительной. Именно эту опцию следует использовать в текущей реализации архитектуры. **Предлагается сделать опцию обязательной?**
2. Да, маршрут сертификации терминала может включать один промежуточный сертификат.  Другими словами, могут быть цепочки двух типов: 1) "корневой сертификат -- сертификат терминала" и 2) "корневой сертификат -- промежуточый сертификат -- сертификат терминала". **Предлагается запретить второй тип?** Обращаю внимание, что в ИОК не принято, чтобы КУЦ выдавали сертификаты напрямую -- теряется гибкость и масштабируемость.
3. Да, в сертификате указывается срок действия (от и до). При проверке цепочки сертификатов терминала на КТ обе даты важны. Например, дата выпуска используется для подстройки оценки текущего времени (на карте может не быть таймера). **Предлагается увязать срок действия сертификатов инфраструктур со сроком действия карты?** Непонятно, что имеется в виду. Действительно, срок окончания действия (до) КТ указывается в дата-группе DG3. Но этот срок не имеет никакого отношения к проверяемой цепочке сертификатов.

**Предложение**:  При положительных ответах на поставленные вопросы создавать дополнительные темы (issue). А эту тему закрыть как чересчур эклектичную.
