### ISSUE TITLE
Режим односторонней аутентификации протокола BAUTH

### ISSUE THREAD

**Issue by andrewkostevich** [bcrypto/btok#38]
Из таблицы 8 следует, что режим односторонней аутентификации в протоколе BAUTH используется только для выполнения следующих операций с  PIN
 * изменения PIN
 * подтверждения PIN
 * разблокировки PIN

Для выполнения остальных операций следует выполнять протокол BAUTH в режиме взаимной аутентификации. То есть одностороннюю аутентификацию нужно выполнять только если заранее известно, что пользователь будет выполнять только упомянутые три операции с PIN. Если априорной информации о операциях пользователя нет, надо выполнять взаимную аутентификацию. Поэтому полезность режима односторонней аутентификации сомнительна, целесообразно его убрать и оставить только режим взаимной аутентификации.

**Comment by olegotory** [comment]
В таблице 8 нет информации о том, должна выполняться односторонняя или взаимная аутентификация по протоколу BAUTH.

В таблице 8:
AS:AT обозначает, что команда должна передаваться после успешного выполнения BAUTH по защищенному соединению, установленному между терминалом и токеном.
AS:CP обозначает, что команда должна передаваться после успешного выполнения BAUTH по защищенному соединению, установленному между клиентской программой и токеном.

Нужна ли взаимная аутентфикация решает терминал (он знает, когда ему важно аутентифицировать карту). Взамная аутентификация обязательно требуется для чтения данных элементарных файлов, например, идентификационных данных (про это сказано в 12.2.5).

**Comment by andrewkostevich** [comment]
Какие APDU команды могут быть выполнены в режиме односторонней аутентификации (ID-карта аутентифицировала терминал, терминал не знает с какой ID-картой общается)?

**Comment by olegotory** [comment]
Должен сам решать терминал. Когда мы читаем данные с карты (в том числе и данные для запроса на выпуск сертификата), то нам важно аутентифицировать карту. Остальные команды можно выполнять с односторонней аутентификацией (иногда анонимность важна, особенное в Европе этим озаботились).

**Comment by andrewkostevich** [comment]
> Когда мы читаем данные с карты (в том числе и данные для запроса на выпуск сертификата), то нам важно аутентифицировать карту.

То есть все функции eID выполняются со взаимной аутентификацией

Функции ЭЦП (генерация ключа, выработка ЭЦП под запросом, установка сертификата) не могут быть выполнены анонимно, требуется аутентификация. Выработка ЭЦП - без аутентификации сервер просто заспамят.

Остаются только функции управления PIN, которые могут быть выполнены анонимно: именно они в таблице 8 и помечены AS:CP.

**Comment by olegotory** [comment]
В генерировании ключей без формирования запроса нет большого смысла.
При выработке ЭЦП под запросом нам нужно почитать предварительно идентификационные данные или специальные данные для запроса. Для чтения обязательно нужна взаимная аутентификация (про это я писал). 
Но почему, например, выработка ЭЦП не может быть с односторонней аутентификацией. Предположим, что я использую какой-то сервер для хранения своих данных с контролем целостности и подлинности. Серверу при этом не обязательно знать, кто именно я такой.

**Comment by andrewkostevich** [comment]
> Но почему, например, выработка ЭЦП не может быть с односторонней аутентификацией. Серверу при этом не обязательно знать, кто именно я такой.

 * Если сервер не аутентифицирует клиента и он принимает команды от всех, то сервер могут просто заспамить (DOS атака): как минимум, сервер делает вычисления BAUTH, как максимум, сервер читает сертификат с карты, строит цепочку сертификатов, проверяет несколько ЭЦП (документ, сертификаты и список отозванных сертификатов. цепочки) - много вычислений
 * Если данные хранятся на сервере, чтобы получить доступ к своим данным на сервере нужно таки аутентифицироваться

В ходе выработки ЭЦП сервер должен вычитать сертификат чтобы сформировать электронный документ в формате CMS

**Comment by olegotory** [comment]
Андрей, ты говоришь про одни сценарии, а я пытаюсь сказать, что могут быть и другие, которые мы сейчас не можем спрогнозировать. Непонятно, что ты пытаешься сказать ... Нужно четко описать, какие команды должны выполняться с взаимной аутентификацией? Это должен не терминал решать, а в стандарте должно быть сказано?

**Comment by andrewkostevich** [comment]
Если априорной информации о операциях, которые намеревается делать  пользователь с ID-картой, нет, то терминалу надо выполнять взаимную аутентификацию.  В результате реализация режима односторонней аутентификации использоваться не будет, а ресурсы карты - которых и так не хватает - она занимать будет.

**Comment by andrewkostevich** [comment]
Режим односторонней аутентификации имеет смысл только для операции выработки ЭЦП при использовании не терминала-сервера, а пользовательского защищенного кард-ридера

**Comment by agievich** [comment]
1. Односторонняя аутентификация "легче" двусторонней. Облегченные решения для нас важны,  поскольку вопрос производительности стоит во главе угла. 
2. Выбор одностороняя/двусторонняя гибкий: его делает терминал по предварительному согласию КТ. 
3. Есть конкретные сценарии, когда односторонняя аутентификации может использоваться вместе двусторонней.
4. Таких сценариев может быть больше. Даже сейчас мы понимаем, что eID и eSign -- это не предел. Могут быть другие прикладные программы, для них может быть важна именно односторонняя аутентификация (анонимность!).

В данной ситуации не вижу смысла отказываться от односторонней аутентификации.

**Comment by agievich** [comment]
*Предложение*: без изменений.
