### ISSUE TITLE
Модификация протокола BAUTH: опциональная отправка сертификата терминала

### ISSUE THREAD

**Issue by andrewkostevich** [bcrypto/btok#42]
Предлагается в APDU инициализации протокола BAUTH добавить возвращаемое значение: issuer and serial сертификата терминала, который имеется на КТ. В случае если у терминала сертификат не изменился, терминал пропускает отправку APDU с сертификатом терминала, КТ в протоколе использует имеющийся сертификат терминала. Если у терминала сертификат изменился - терминал отправляет APDU с сертификатом терминала, КТ его сохраняет для дальнейшего использования. В результате в течение срока действия сертификата терминала трудоемкий шаг отправки терминала и  проверки его подлинности выполняется только один раз.

**Comment by olegotory** [comment]
Терминалов много (не один и не два). Более того, обычно срок действия сертификатов терминалов короткий, макс. 3 месяца (так как СОС не используются). Поэтому предложение не поддерживаю.

**Comment by agievich** [comment]
Идет речь о кэшировании сертификатов терминалов. Но мы никогда не предполагали, что сертификаты терминалов кэшируются на борту КТ. Целесообразность такого кэширования имеется (ускорение быстродействия), но есть и очевидные встречные вопросы: сколько сертификатов кэшировать? какие сертификаты кэшировать? ссылку какой из кэшированных сертификатов отправлять? Ответы на вопросы неоднозначны, потому что терминалов действительно может быть много, их сертификаты могут часто обновляться.

Если поставленные вопросы отдать на откуп реализации, то почему бы не воспользоваться следующей стратегией в рамках действующей системы APDU-команд:
1) КТ получает сертификат терминала;
2) КТ сравнивает его с сертификатами из списка кэшированных;
3) если найдено совпадение, то ЭЦП сертификата не проверяется, только срок действия.

**Предложение**: без изменений.

**Comment by andrewkostevich** [comment]
В случае согласования необходимости отправки сертификата трудоемкость протокола **существенно** снижается: в зависимости от платформы, общая длительность аутентификации снижается на 25%-40%.

Трудоемкость протокола снижается на 25-40% без изменения криптографической схемы, только за счет системы команд.

**Comment by agievich** [comment]
Еще раз опишу ситуацию. Протокол BAUTH реализуется 4 командами:
1) инициализация (MSE: Set AT);
2) проверка сертификата терминала (PSO: Verify Certificate);
3) основные шаги (General Authenticate);
4) оставшиеся основные шаги (General Authenticate).

Предлагается отказаться от команды 2 в определенных обстоятельствах. Мотивация: отказ экономит 25 - 40% времени.

*Определенные обстоятельства*: КТ уже получил раньше сертификат терминала, проверил его, сохранил, сертификат не изменился. Обстоятельства кажутся довольно искусственными, потому что терминалов может быть много, их сертификаты часто меняются. Но, тем не менее, с вероятностью p КТ попадет на нужный терминал и сэкономит 25-40% времени.

Высока ли плата за экономию? Для меня, да, довольно высока. Потому что теряется общий смысл BAUTH (каждый с каждым), возникает довольно туманный механизм кэширования сертификатов. Если уже быть до конца последовательным, то следует от механизма "Кэширование сертификатов" переходить к механизму "Возобновлению сессии" (в стиле TLS), т.е. пытаться возобновить созданное ранее SM. Вот тогда экономия будет существенной. Но выглядит "Возобновлению сессии" довольно странно, хотя это логическое продолжение "Кэширования сертификатов".

Я уже писал, что в конкретной реализации КТ можно кэшировать сколько угодно сертификатов, сохранять ход BAUTH, но только не проверять присланный сертификат, а сравнивать его с кэшированными. Парсинг не нужен! Разве даже в такой ситуации будет 25-40% экономии?

**В целом** считаю, что "Кэширование сертификатов" является спорным механизмом, преимущества которого проявляются только в специфических условиях привязки к конкретному терминалу с конкретным сертификатом. В этих условиях возможно развертывание других механизмов с еще большими преимуществами.  Платой за развертывание является загромождение и так уже довольно сложной архитектуры КТ. Механизм не поддерживаю. Если компромисс не найден, давайте выносить issue в список проблемных.

**Comment by andrewkostevich** [comment]
Схема протокола не меняется: доказательство владения личным ключом в сеансе терминала остается. 

Сколько и каких будет терминалов - это вопрос инфраструктуры. Архитектура КТА должна позволять (не должна запрещать) создавать эффективные инфраструктуры. Если, как пишет @olegotory, сертификат терминала издается до 3 месяцев, то при определенном выборе инфраструктуры пользователь получит экономию времени выполнения в течение всего этого срока. 

В худшем случае быстродействие КТ не уменьшится (терминал будет отправлять свой сертификат в каждом сеансе), в лучшем случае - увеличится на 25-40% (во всех сеансах, кроме первого после выпуска нового сертификата терминала, сертификат не будет отправляться).

**Comment by agievich** [comment]
>Архитектура КТА должна позволять (не должна запрещать) создавать эффективные инфраструктуры.

Смотря что понимать под эффективностью. Да, мы можем вводить новые и новые механизмы (почему бы не рассмотреть "Возобновление сессии"), но, как мы знаем, complexity is the worst enemy of security.  
Я думаю, что здесь мы столкнулись с методологическим вопросом, предлагаю вынести его в список проблемных (вместе с #43 и #18) и поставить пока точку.

**Comment by alexshibkov** [comment]
Про срок действия сертификата терминала. Например, по требованиям ICAO сертификат терминала (для доступа к группе, содержащей графическое отображения отпечатков пальцев) обновляется раз в сутки.

**Comment by andrewkostevich** [comment]
Кэширование сертификатов: 
 * опционально поддерживается в TLS версии 1.2 путем использования расширения [RFC 7924: Transport Layer Security (TLS) Cached Information Extension](https://tools.ietf.org/html/rfc7924)
 * поддержка явно включена в версию 1.3 TLS [RFC 8446: The Transport Layer Security (TLS) Protocol Version 1.3](https://tools.ietf.org/html/rfc8446)

**Comment by agievich** [comment]
Ходим по кругу. Если проводить параллели с TLS, то почему не рассмотреть возобновление связи (session resumption)? Напомню, что на обсуждение вопроса объявлен мораторий.

**Comment by agievich** [comment]
**Закрывается**. Механизм кэширования сертификата терминала усложняет архитектуру, повышая эффективность только в спорной конфигурации "терминалов буде мало и их сертификаты будут долговременными".
