### ISSUE TITLE
Модификация протокола BAUTH: опциональная отправка сертификата КТ

### ISSUE THREAD

**Issue by andrewkostevich** [bcrypto/btok#43]
Терминал может иметь доступ к базе сертификатов КТ, может кэшировать сертификаты КТ, поэтому в протоколе BAUTH терминалу надо знать только issuer and serial сертификата КТ. Варианты: 
 * в APDU инициализации BAUTH терминал выбирает что он хочет получить на шаге M3: сертификат КТ или только issuer and serial сертификата 
 * всегда на шаге M3 отправлять issuer and serial сертификата КТ и добавить в файловую систему КТ сертификат КТ. Терминал сможет считать сертификат командой чтения файла, если сертификат ему потребуется. 

Второй вариант более универсальный, также снижает ограничения на объем сертификата.

**Comment by olegotory** [comment]
Как отмечено, терминал может иметь, а может и не иметь доступа к базе сертификатов КТ. 
Тогда непонятно в чем экономия: 1) сообщение М3 все равно отправляется; 2) мы ранее договорились, что сертификат будет влезать в M3, т.е. проблем с объемом сертификата КТ нет.
Более того, усложняется логика и, следовательно, реализация КТ и терминала.
Предложение не поддерживаю.

**Comment by agievich** [comment]
Если база данных есть, то терминал может проверить наличие в ней присланного сертификата КТ. Вместо проверки ЭЦП. И изменение команд не требуется.

**Предложение**: без изменений.

**Comment by andrewkostevich** [comment]
В случае замены отмены сертификата на меньший объем информации трудоемкость шага протокола **существенно** снижается: в случае отправки сертификата имеет место двухкратное шифрование и выработка имитовставки от 180 байт (один раз - в BAUTH, второй раз - в Secure Messaging, установленный BPACE)

**Comment by agievich** [comment]
Та же ситуация, что в #42: экономия онлайн-времени достигается за счет кэширования сертификатов. Экономия снова возможна в весьма специфических условиях. Требуется налаживать взаимодействие терминалов с гипотетическими базами данных сертификатов: снова аутентификация, защищенное соединение. Общие преимущества не очевидны. Если компромисс не найден, вопрос надо выносить в список проблемных вместе с #42.

**Comment by andrewkostevich** [comment]
Самым слабым звеном в протоколе является КТ, увеличение быстродействия достигается за счет уменьшения вычислительной нагрузки на самое слабое звено (за счет перекладывания части операций на более производительные стороны). Терминал сам решит, в каком режиме ему работать: он запросит у КТ либо certHolderReference либо сертификат целиком.

**Comment by agievich** [comment]
> Терминал сам решит, в каком режиме ему работать.

Боюсь, что когда дойдет до терминала (и его разработчиков), решение будет в пользу простоты, а не 10% экономии времени КТ. Снова предлагаю объявить вопрос как проблемный и сделать паузу.

**Comment by agievich** [comment]
> Терминал может иметь доступ к базе сертификатов КТ, может кэшировать сертификаты КТ, поэтому в протоколе BAUTH терминалу надо знать только issuer and serial сертификата КТ.

Под `issuer and serial number` подразумевается `certAuthorityReference + certHolderReference`? Тогда это 20 октетов. Сам сертификат КТ (на подразумеваемом уровне l = 128) состоит из 188 октетов. Экономится передача 188 - 20 = 168 октетов. Разумна ли плата за такую экономию?

**Comment by agievich** [comment]
**Закрывается**. Механизм кэширования сертификатов КТ существенно усложняет архитектуру терминалов, несущественно повышая эффективность.
