### ISSUE TITLE
Получение информации о сертификате eSign

### ISSUE THREAD

**Issue by andrewkostevich** [bcrypto/btok#50]
Для исключения чтения сертификата при каждой выработке ЭЦП требуется механизм получения идентификатора сертификата, соответствующего личному ключу, выбранному в eSign для выработки ЭЦП: 
 * добавить в файловую систему eSign файлы, хранящие идентификатор соответствующего личного ключа (например, SKID)
 * определить правила формирования идентификатора: при генерации самостоятельно программой eSign (как SKID, предпочтительнее), генерация терминалом и запись в файл или др.

Это позволит терминалу оптимизировать работу с сертификатами: кэшировать, получать из каталога ГосСУОК

**Comment by agievich** [comment]
Требуются комментарии. КТ не использует сертификаты при выработке ЭЦП. Нужный лк идентифицируется одним байтом в команде выработки ЭЦП. Соответствующие сертификаты действительно *могут* храниться в пределах криптографической границы КТ (6.5). Используется простейшая схема именования файлов, в которых они хранятся (таблица Б.1): идентификатор лк продолжается в FID.

**Comment by andrewkostevich** [comment]
Терминалу для формирования CMS/PKCS7 нужен сертификат. Наличие идентификатора позволит оптимизировать работу с сертификатами: получать из каталога ГосСУОК, кэшировать вместо чтения каждый раз с карты

**Comment by agievich** [comment]
> Терминалу для формирования CMS/PKCS7 нужен сертификат.

Терминал подписывает документ с помощью КТ, формирует CMS-контейнер, вкладывает в него сертификат КТ. Правильно ли я понимаю, что речь идет о том, что вместо чтения сертификата с КТ предлагается получать сертификат из каталога ГосСУОК?

Отмечу, что в BPKI не предусмотрен сервис получения сертификатов по идентификатору. Целесообразность поддержки таких сервисов является дискуссионной.

**Comment by andrewkostevich** [comment]
Есть еще кэширование

**Comment by olegotory** [comment]
В терминальном режиме с взаимной аутентификацией при выполнении bauth КТ передает терминалу сертификат. В терминальном режиме для каждого уровня может использоваться только один ключ, которому соответствует один сертификат (на практике сейчас будет использоваться только ключ для уровня l=128). При необходимости терминал может один раз прочитать сертификат подписи и установить соответствие между сертификатом аутентификации КТ и сертификатом ключа подписи. В этом случае терминалу не потребуется каждый раз читать сертификат, если у него уже такой сертификат есть и он ранее установил необходимое соответствие. Отмечу, что в терминальном режиме ключ (и соответственно уровень) выбирает терминал.

**Comment by agievich** [comment]
> Есть еще кэширование

Технически несложно добавить функционал хранения SKID на КТ. Фактически, достаточно просто расширить таблицу Б.1. Теперь, при расширении функционала, терминал прочитывает SKID (20 байтов) вместо сертификата (\approx 1000 байтов), а затем находит сертификат по SKID в своем списке кэшированных сертификатов. Но, действительно,  если список кэшированных сертификатов есть, то индексировать его можно по серийному номеру в CV-сертификате, и тогда SKID вообще не нужно прочитывать.

**Comment by agievich** [comment]
Хочу обратить внимание, что в данном issue, а также в #42, #43 предлагается примерно одно и то же: не передавать сертификаты, если они были переданы и сохранены ранее. Идет речь о передаче: облегченного сертификата терминала (#42), облегченного сертификата КТ (#43), обычного сертификата КТ (#50).

Идея понятна --- сокращение времени выполнения криптографических операций. Понятна и плата --- до этого stateless-криптографические устройства становятся stateful. Теперь их функционирование определяется не только текущей online-ситуацией, но и прошлой историей. 

Ничего особенно плохого в stateful-функционале нет, но и особенных плюсов я не вижу. Да, мы экономим в конкретной ситуации, но проигрываем в долгосрочной перспективе (это сродни допингу в спорте). Почему проигрываем? Потому, что stateful-функционал (в нашем случае и по моему мнению): a) громоздкий; б) непрозрачный; в) неунифицированный. Stateless-функционал кажется более подходящим, потому что он простой и управляемый, проще верифицируемый.

И еще. Если уж быть до конца последовательным, то надо делать stateful-функционал до конца stateful. Нужно кэшировать не сертификаты, а состояния защищенных соединений. Так поступают в протоколах с большой нагрузкой на сервер (TLS, session resumption). Но я не думаю, что это наш случай, по-крайней мере, что нам стоит сейчас этим заниматься.

**Comment by andrewkostevich** [comment]
> Технически несложно добавить функционал хранения SKID на КТ. 

Давайте добавим

> Фактически, достаточно просто расширить таблицу Б.1. 

таблицу Б.2

> Но, действительно, если список кэшированных сертификатов есть, то индексировать его можно по серийному номеру в CV-сертификате, и тогда SKID вообще не нужно прочитывать.

 1. Есть режим локальной выработки ЭЦП, в котором CV сертификата КТ просто нет 
 1. Может быть режим односторонней аутентификации BAUTH, в котором CV-сертификата КТ тоже нет. Если режим односторонней аутентификации BAUTH не использовать для выработки ЭЦП, то смысл в этом режиме исчезнет окончательно (см. обсуждение в #38)

> Ничего особенно плохого в stateful-функционале нет, но и особенных плюсов я не вижу.

Это ничего не убавляет, зато существенно прибавляет возможности для инфраструктуры терминалов

**Comment by agievich** [comment]
> 1. Есть режим локальной выработки ЭЦП, в котором CV сертификата КТ просто нет

Как в базовом режиме (так говорится в BTOK) будут кэшироваться сертификаты КТ? Как будет защищаться кэш? Как будут обеспечиваться гарантии соответствия сертификата в кэше и актуального сертификата? До этого в потенциально небезопасной среде (для защиты от рисков которой и разрабатываются КТ) циркулировали (**одномоментно**) только пароли. Теперь переносим туда (**надолго**) и сертификаты. 

> Это ничего не убавляет, зато существенно прибавляет возможности для инфраструктуры терминалов.

Возможности дискуссионны. Пока речь только о том, что нагрузка на терминалы увеличивается.

**Подводя итоги.** Cерия предложений (#42, #43, #50) ориентирована на ускорение работы КТ через некриптографические механизмы кэширования объектов, от которых зависит безопасность. Вопросы управления этими объектами (в том числе защиты на стороне КП) отодвигаются. Stateless-архитектура становится stateful, многое загромождается. При этом предлагаемые решения являются половинчатыми. Если быть до конца последовательным и бороться за производительность всеми силами, то нужно кэшировать защищенные соединения (на стороне КТ и терминала). 

Я думаю, что вопрос достаточно обсужден. Консенсус не выработан. Вопрос помечается как проблемный и присоединяется к #42, #43 по общей темой "Stateless vs stateful".

**Comment by agievich** [comment]
Предложенный функционал реализован в #53.
