### ISSUE TITLE
Уточнение групп данных

### ISSUE THREAD

**Issue by olegotory** [bcrypto/btok#52]
Для соответствия групп данных, определенных в стандарте, согласованному набору групп данных предлагается в стандарт внести изменения:
1. Вместо названия группы данных "Личный номер" писать "Идентификационный номер".
2. В группах DG4 - DG6 дополнительно указывать информацию на латинице.
3. Для группы DG9 описание компонента city изложить в следующей редакции: 
  "компонент city должен содержать название населенного пункта (города, поселка, деревни и т.п.)"

**Comment by agievich** [comment]
Реализовано в a3c55e906ea0f9bb90bf6e85f8be769cc792a630
