### ISSUE TITLE
Неоднозначное определение серийного номера сертификата

### ISSUE THREAD

**Issue by andrewkostevich** [bcrypto/btok#55]
> Если  же субъектом является КТ или терминал, то в certHolderReference задается серийный номер.

Из текста стандартно не ясно, связан ли серийный номер сертификата КТА с серийным номером КТА. Требуются пояснения: процедура персонализации КТА зависит от наличия/отсутствия такой связи.

**Comment by agievich** [comment]
Конечно, речь идет о серийном номере КТ / терминала. Кажется, что такое понимание безальтернативно: 
1. Словосочетание "серийный номер" используется в BTOK только в контексте "серийный номер КТ/терминала".
2. В BTOK нет упоминаний о серийном номере сертификата. Если объект ни разу упоминается, то нет смысла объяснять, что мы не имеем его в виду.

**Comment by agievich** [comment]
Перенесено в #56.
