### ISSUE TITLE
Тип CVDate сертификата отличается от международного ICAO

### ISSUE THREAD

**Issue by andrewkostevich** [bcrypto/btok#57]
Тип CVDate из стандарта отличается от типа Date MRTD:
 * В стандарте CVDate формат определен через NumericString: последовательность цифр в кодировке ASCII, примеры сертификатов соответствуют NumericString
 * Для облегченных сертификатов MRTD формат Date определен как последовательность цифр в формате `unpacked BCD`: A date is encoded in 6 digits d 1⋯d 6 in the format YYMMDD using timezone GMT. It is converted to an octet string o1⋯o6 by encoding each digit d j to an octet oj as unpacked BCDs 1≤ j≤6

**Comment by olegotory** [comment]
Согласен. Кодирование в облегченном сертификате значений типа NumericString и значений в формате unpacked BCD будет отличаться.

**Comment by agievich** [comment]
Да, здесь несоответствие (ср. например с https://www.befreite-dokumente.de/www.befreite-dokumente.de/eingereichte-akten/tr-03110-eac-1.0/attachment_download/publication_download.pdf). Желательно исправить. Помечаю вопрос как проблемный.

**Comment by agievich** [comment]
Предлагаются следующие корректировки:
1. `CVDate ::= OCTET STRING(SIZE(6))`.
2. При описании формата `CVDate` дописать (после "Дата задается строкой формата YYMMDD..."): 
> Символы строки --- десятичные числа $0,1,\ldots,9$ --- кодируются октетами \hex{00},\hex{01},\ldots,\hex{09}.
3. При описании `certExpirationDate` заменить "время окончания действия" на "дату окончания действия".

**Comment by agievich** [comment]
Реализовано в https://github.com/bcrypto/btok/commit/ff8e28b98df002a426e7b3f5b70aeba06d8a8035.
