### ISSUE TITLE
Код региона (DistrictID): код СОАТО вместо почтового индекса

### ISSUE THREAD

**Issue by andrewkostevich** [bcrypto/btok#59]
Использование почтового индекса в качестве содержания группы данных DG17 не оправдано:  почтовый индекс не позволяет отнести гражданина к административно-территориальной единице и соответственно не позволяет установить права гражданина в этой административно-территориальной единице (например, голосовать, писать жалобу или иметь право бесплатного проезда). 

Более правильно использовать код СОАТО, который как раз предназначен для этого. Классификатор СОАТО: Система обозначений объектов административно-территориального деления и населенных пунктов http://nca.by/rus/geosystem/partition/classificatorsoato.txt

**Comment by olegotory** [comment]
Насколько я понял, для города код СОАТО позволяет задать информацию, в которой минимальной административно-территориальной единицей является городской район. Информация по СОАТО получается малоинформативной.

**Comment by andrewkostevich** [comment]
Минимальной единицей является сельский населенный пункт, см. разъяснения http://nca.by/rus/geosystem/partition/classificatorsoato.txt, последние 3 символа кода СОАТО

**Comment by olegotory** [comment]
Я писал для города (см. мое сообщение).

**Comment by andrewkostevich** [comment]
Согласен, СОАТО дает хорошее разрешение по стране, но внутри города не дает детализации, внутри города - наверное, нужное разрешение только адрес проживания (например для голосования).

**Comment by olegotory** [comment]
Группа DG17 с одной стороны должна обеспечивать анонимность, а с другой стороны -- давать ограниченную информацию о месте проживании (т.е. не раскрывать полный адрес проживания). Для этих целей было принято решение указывать индекс.

**Comment by andrewkostevich** [comment]
Проблемы использования почтового индекса:
 * это внутренний белпочтовский классификатор (недоступен остальным), СОАТО - государственный общедоступный классификатор
 * не соответствует административно-территориальным единицам: на его основе нельзя принять решение о правах в административно-территориальной единице
 
С другой стороны, СОАТО имеет недостаток - низкое разрешение внутри города (до района) - но более высокое разрешение - это все-таки уже адрес.

**Comment by agievich** [comment]
> Согласен, СОАТО дает хорошее разрешение по стране, но внутри города не дает детализации, внутри города - наверное, нужное разрешение только адрес проживания (например для голосования).

> С другой стороны, СОАТО имеет недостаток - низкое разрешение внутри города (до района) - но более высокое разрешение - это все-таки уже адрес.

Так все-таки, предлагается использовать COATO или не предлагается?

**Comment by andrewkostevich** [comment]
Окончательной целью eID является реализация электронного правительства: с этой точки зрения СОАТО является более адекватным кодом региона

**Comment by agievich** [comment]
> Окончательной целью eID является реализация электронного правительства

Стандарт BTOK не претендует на такой масштаб. 

Считаю, что код COATO, который уравнивает  скажем всех жителей Фрунзенского района города Минска (около полумиллиона жителей), малоинформативен. Почтовый индекс -- это очень хорошее решение для примерной (именно такая и нужна!) проверки локации. Других разумных на данный момент кодов локации я не вижу. 

В любом случае предложение недостаточно проработано. Не продуманы все детали, не учтено, что ссылка на упомянутный классификатор не соответствует концепции ТНПА (система стандартов должна быть герметична, ссылки на законы, постановления, ведомственные документы недопустимы) и может быть заблокирована Госстандартом. Впредь рекомендуется давать предложения в более отчетливой форме. Желательно в виде PR.

**Предложение**: без изменений.

**Comment by agievich** [comment]
В https://github.com/bcrypto/btok/commit/1da29c9f76e9dea49fc3054b5e83fcd6713e0e23 указание почтового индекса в `DistrictID` сделано рекомендательным.

**Comment by andrewkostevich** [comment]
Все таки хотелось бы обратить внимание: в eIDAS DistrictID называется MunicipalityID, где 

> A municipality is usually a single administrative division having corporate status and powers of self-government or jurisdiction as granted by national and regional laws to which it is subordinate. 

что решает именно задачи электронного взаимодействия с органами местного управления и целиком соответствует нашему коду СОАТО
