### ISSUE TITLE
Поддержка уровней стойкости 192/256 в eID

### ISSUE THREAD

**Issue by andrewkostevich** [bcrypto/btok#60]
> Алгоритмы bash384, bash512. Используются алгоритмы хэширования bash384,
bash512, определенные в СТБ 34.101.77. ... КТ получает уже готовые хэш-значения и поэтому не должен реализовывать алгоритмы.

КТ получает уже готовые хэш-значения только при выработке ЭЦП. КТ в BUATH должен проверять ЭЦП сертификата терминала. Если КТ не реализует bash, то, получается,  КТ не может проверить ЭЦП и не может поддержать уровни стойкости 192/256?

**Comment by agievich** [comment]
Фраза "КТ получает уже готовые хэш-значения и поэтому не должен реализовывать алгоритмы" некорректна. Нужно выпускать поправку.

**Comment by agievich** [comment]
Предлагается следующая формулировка: 
> КТ может не реализовывать алгоритмы, если не предполагается проверка облегченных сертификатов (см. раздел 9), подписанных на ключах уровней стойкости =192 и l=256.

**Comment by agievich** [comment]
Реализовано  в https://github.com/bcrypto/btok/commit/ff8e28b98df002a426e7b3f5b70aeba06d8a8035.
