### ISSUE TITLE
Тип Place не позволяет описать место рождения в структурированном виде

### ISSUE THREAD

**Issue by andrewkostevich** [bcrypto/btok#62]
Тип Place не позволяет описать место рождения в структурированном виде, не хватает: 
 * района
 * типа населенного пункта

**Comment by andrewkostevich** [comment]
Структуру места рождения нужно согласовывать с ДГИМ МВД: обязательный и необязательный перечень полей

**Comment by olegotory** [comment]
Все группы данных и применяемые типы согласовывались с различными гос. органами, в том числе и МВД. Этим занимался ОАЦ. В стандарте были учтены все изменения, сделанные по результатам согласования (согласно переданному нам документу). 

Можно в стандарте сказать, что для типа Place в компоненте state задается область и район.
Тип населенного пункта может определяться из контекста данных: если начинается с г. -- значит город, д. -- деревня и т.п. 

**Предложение**:  сказать в стандарте, что в state задается область и район -- в случае рождения владельца в Республике Беларусь.

**Comment by agievich** [comment]
В https://github.com/bcrypto/btok/commit/1da29c9f76e9dea49fc3054b5e83fcd6713e0e23 детализованы правила заполнения полей `Place`.
