### ISSUE TITLE
Перейти к формату TLV для файла SKID

### ISSUE THREAD

**Issue by andrewkostevich** [bcrypto/btok#64]
Файл со SKID хранит неформатированные данные длиной 20 или 32 байта. Целесообразно перейти к формату TLV с типом OCTET STRING:
 * содержание файла имеет неизвестную длину: формат TLV более естественный в этом случае
 * все файлы в стандарте кроме файла со SKID имеют формат TLV
 * при чтении за одну команду (#54 ) должен возвращаться TLV объект

**Comment by agievich** [comment]
Да, можно перейти:

> Хэш-значение `h` состоит из 20 или 32 октетов. Хранится в видет строки `der(tag, h)`.

Остается определиться с `tag`. Это либо 0x04 (OCTET STRING), либо специальный тег, как это принято в BTOK и базовых стандартах.

**Comment by andrewkostevich** [comment]
Другие данные eSign (сертификаты и Name) хранятся в форматах СТБ 34.101.19 и в этом случае OCTET STRING вполне логичен, есть некоторый шанс, что терминал или КП смогут воспользоваться SKID сразу в виде TLV без его парсинга. В случае специального тэга терминалу или КП обязательно придется парсить TLV. Хотя ничего плохого в специальном тэге нет.

**Comment by agievich** [comment]
Реализовано в https://github.com/bcrypto/btok/commit/d242e3f1579adbb43ce0f6521dfd07a9e1f87823 в редакции:
> Хэш-значение H состоит из 20 или 32 октетов. Хранится в виде строки der(04_16, H).
