### ISSUE TITLE
Какое назначение у команды деактивации PIN?

### ISSUE THREAD

**Issue by andrewkostevich** [bcrypto/btok#69]
Какое назначение у команды деактивации PIN? Изначально PIN активирован, после деактивации PIN его можно только активировать то есть вернуть в предыдущее состояние. В условиях изначально активированного PIN не понятно, какая задача решается командами деактивации/активации PIN.

**Comment by olegotory** [comment]
Деактивировать PIN  может понадобиться, например, в следующих случаях:
1. Владелец хочет временно деактивировать свою карту по каким-либо причинам.
2. Терминал обнаружил, что перед ним аутентифицируется карта, которая в списке отозванных.
Отмечу, что активировать PIN можно только по PUK.

**Comment by andrewkostevich** [comment]
> Терминал обнаружил, что перед ним аутентифицируется карта, которая в списке отозванных.

Если решать задачу отзыва карты, то нужно говорить о необратимой операции отзыва,  а не об обратимой операции деактивации PIN. В частности, по европейской спецификации eSign предусмотрены конкретные операции для отзыва карты: деактивация и блокировка приложения eSign целиком.

> Владелец хочет временно деактивировать свою карту по каким-либо причинам.

Какие-либо причины - это субъективно. Вопрос в наличии объективной необходимости деактивировать, а потом активировать PIN? 

В частности, в той же европейской спецификации eSign активация/деактивация PIN есть и используется для активации _отдельного_ PIN для eSign (конкретная объективная задача). 

То есть APDU активации/деактивации PIN имеют смысл, но только в случае определенной конфигурации КТ. В случае eIDAS токена - это возможность ввести (активировать) отдельный локальный PIN для eSign. 

В условиях стандарта - один активированный PIN без опциональной возможности ввода второго PIN - эти команды не несут полезной нагрузки.

**Comment by agievich** [comment]
Сначала был задан вопрос о назначении механизма деактивации PIN. На него был дан ответ: деактивация является полублокировкой КТ и может использоваться как владельцем (уезжаю в отпуск, оставляю КТ в потенциально агрессивной среде), так и терминалом (реакция на тревожное событие).

Теперь идет критика, которую трудно понять. О чем речь? Деактивация не нужна? Деактивация плохо спроектирована? Есть конкретные предложения?

Что касается отзыва КТ. Отзыв был только примером тревожного события. Да, при отзыве терминал и вся инфраструктура могут выполнять другие действия, например, деактивировать ключи eSign. Но эти действия не относятся к обсуждаемому вопросу.

**Comment by andrewkostevich** [comment]
Это не критика: разрабатывается "профиль" для идентификационной карты и отбираются команды для обязательной реализации в идентификационной карте. Задачи, решаемые командами деактивации/активации PIN, не были ясны. Теперь задачи выяснены и будет приниматься решение о поддержке этих команд
