### ISSUE TITLE
Время жизни результата проверки CAN

### ISSUE THREAD

**Issue by andrewkostevich** [bcrypto/btok#71]
Если счетчик попыток PIN равен 1, то следует проверить CAN. Какое время жизни результата проверки CAN: ограничено сеансом или должно храниться между сеансами? 

1. Если время жизни результата ограничено сеансом, если сеанс завершен без проверки PIN при начале следующего сеанса следует опять проверять CAN.
1. Если результат хранится между сеансами, если сеанс завершен без проверки PIN при начале следующего сеанса не требуется проверять CAN.

**Comment by agievich** [comment]
При определении логики работы с PIN/PUK/CAN (6.3) слово "сеанс" не употребляется. Поэтому непонятно, о каком сеансе идет речь. Конечно, счетчики попыток являются глобальными.

**Comment by agievich** [comment]
В BTOK достаточно последовательно реализовывалась "плоская" модель работы с КТ: токен готов обработать команду в любой момент времени, для отправки команды не требуется выполнять инициализацию, открывать сеанс работы и т.д. 

Поэтому термины "сеанс", "сеансовый" встречаются только в контексте протоколов BPACE, BAUTH. Последние неточные (вне рамок "плоской" модели) применения терминов подавлены при реализации issue #74.

Но сеансы, хоть и подавленные в модели, все равно остаются на практике. И могут возникать вполне резонные вопросы о "сеансовости" некоторых объектов. К счастью, пока только одного объекта -- "признака активации CAN". И как раз этот объект делать сеансовым совсем не стоит. Ведь предъявляя правильный CAN, мы сразу же (в текущем сеансе) возобновляем PIN. Нелогично снова приостанавливать только что возобновленный (и еще не проверенный) пароль по окончании сеанса.

Вопрос **закрывается** без изменений в BTOK.
