### ISSUE TITLE
Неоднозначность правил перехода AS->PS

### ISSUE THREAD

**Issue by andrewkostevich** [bcrypto/btok#75]
> В состояние PS токен может перейти из ... состояния AS при принудительном закрытии защищенного соединения «терминал — КТ» (см. 12.4). При переходе в PS существующее защищенное соединение «КП — КТ» переустанавливается, а защищенное соединение «терминал — КТ» закрывается

Что имеется в виду под _переустановкой_ защищенного соединения «КП — КТ»: переключение на ключевой набор, созданный в BPACE, или сброс КТ в состояние IS и необходимость повторного  выполнения протокола BPACE?

**Comment by olegotory** [comment]
Под переустановкой существующего защищенного соединения понималось, что для защиты должны использоваться новые ключи, которые только что были сформированы в рамках выполнения протокола. 

Учитывая, что в состояние PS может быть переход из состояния AS при принудительном закрытии защищенного соединения «терминал — КТ», **предлагается** вместо:

> При переходе в PS существующее защищенное соединение «КП — КТ» пере-
устанавливается, а защищенное соединение «терминал — КТ» закрывается.

написать:

> После успешной парольной аутентификации существующее защищенное соединение «КП — КТ» переустанавливается, а существующее защищенное соединение «терминал — КТ» закрывается.

**Comment by agievich** [comment]
Предлагается раскрыть "переустанавливается" (именно по этому термину был вопрос):

>После успешной парольной аутентификации существующее защищенное соединение «КП — КТ» 
переустанавливается (устанавливаются новые ключи, полученные с помощью BPACE), а существующее защищенное соединение «терминал — КТ» закрывается.

**Comment by agievich** [comment]
**Реализовано** в https://github.com/bcrypto/btok/commit/0a7dc32d333b1a24b938939c9f960a82776f74a3.
