### ISSUE TITLE
Некорректный код ошибки BAUTH

### ISSUE THREAD

**Issue by andrewkostevich** [bcrypto/btok#76]
Выполнение шага протокола BAUTH может завершиться ошибкой, в этом случае возвращается код `6300` "протокол (шаг) выполнен с ошибкой". 

В ISO 7816 код `6300` относится к предупреждениям и означает "State of non-volatile memory has changed". 

Непонятно, какой долговременный параметр должен поменяться при неудачном выполнении протокола или использован неподходящий код возврата

Код ошибки должен быть аналогичен коду ошибки проверки сертификата: это тоже шаг протокола который может быть завершен с ошибкой

**Comment by olegotory** [comment]
**Предлагается:**
1. Для команды выполнение шага протокола BAUTH убрать код 6300.
2. Для команды проверки дополнительного атрибута заменить код 6300 на 6200.

**Comment by olegotory** [comment]
**Реализовано** в https://github.com/bcrypto/btok/commit/51f1bd381393836ff851329a77a0e30f252b603d
