### ISSUE TITLE
Неполная спецификация ошибок BPACE в случае неверных PUK/CAN

### ISSUE THREAD

**Issue by andrewkostevich** [bcrypto/btok#77]
В случае ошибки в протоколе BPACE при аутентификации по CAN: что возвращать в случае неверного CAN?
 * 63CF так как число оставшихся попыток (бесконечность) больше 15? 

В случае ошибки в протоколе BPACE при аутентификации по PUK при незаблокированном PIN: что возвращать в случае неверного PUK?
 * 63CF так как число оставшихся попыток (бесконечность) больше 15?
 * 63CA для индикации 10 попыток?

В случае ошибки в протоколе BPACE при аутентификации по PUK при заблокированном PIN: что возвращать в случае неверного PUK?
 * 63CF так как число оставшихся попыток (бесконечность) больше 15?
 * 63C9...63C0 для предупреждения пользователя о числе оставшихся попыток перед блокировкой PIN навсегда? В этом случае код 63CA в предыдущем случае выглядит более логичным

В случае ошибки в протоколе BPACE при аутентификации по PUK при заблокированном PIN навсегда: что возвращать в случае неверного PUK?
 * 63C0 для предупреждения пользователя о том что PIN уже заблокирован навсегда?
 * 63CF так как число оставшихся попыток (бесконечность) больше 15? 

Этот код должен быть увязан с кодом возврата _перед_ блокировкой PIN навсегда: если был возвращен 63C0 то возврат другого (большего) значения уже выглядит нелогично

**Comment by agievich** [comment]
Разве PR #73 недостаточно?

**Comment by agievich** [comment]
Логика информирования о неверных PUK/CAN реализована в #73.
