### ISSUE TITLE
Зависимости между отдельными правами доступа eID и eSign

### ISSUE THREAD

**Issue by andrewkostevich** [bcrypto/btok#78]
* Наличие у терминала права чтения сертификата eSign раскрывает значение Name, доступ на чтение к которому ограничивается отдельным правом доступа eSign
 * Наличие у терминала права чтения Name или сертификата eSign раскрывает часть идентификационных данных eID (ФИО), доступ на чтение к которым ограничивается отдельными правами доступа eID

**Comment by agievich** [comment]
Да, следует учитывать зависимости при планировании прав доступа.

Следует понимать, что права доступа BTOK регулируют синтаксис -- доступ к объектам, -- но не семантику -- содержание, "смысл" объектов.
