### ISSUE TITLE
Выпуск билета аутентификации

### ISSUE THREAD

**Issue by NikGomel** [bcrypto/btok#87]
В стандарте предусмотрено, что на шаге 2 пользователь дает согласие на получение его данных формируя перечень ChartB, после чего начинается аутентификация пользователя на СИ. В спецификации OpenID Connect данный шаг вынесен после процедуры аутентификации пользователя на сервере идентификации. С чем связано перенос данной процедуры на более ранний этап?

**Comment by agievich** [comment]
Да, перечень Chart_B (права доступа к представляемым id-данным) согласуется в самом начале -- в момент аутентификации КП - КТ через BPACE. "Раннее согласие" (так это можно назвать) значительно упрощает взаимодействие в четырехугольнике КП - Т - КТ -СИ:
1. СИ, получив Chart_B, может выбрать Т с подходящими правами.
2. КТ, разбирая цепочку сертификатов Т, может построить интегральное слово прав доступа.
3. После аутентификации КТ - Т терминалу не нужно переключать КТ на соединение с КП. Именно через это соединение владелец КТ должен согласовать Chart_B. После согласования КП должна вернуть КТ на соединение с Т. Очень громоздко. Более того, только теперь КТ может построить слово прав доступа и, следовательно, нужно кэшировать права в сертификатах цепочки. Более того, переключение между соединениями предполагает наличие канала управления между Т и КП. По хорошему, этот канал нужно защищать (TLS), а мы старались построить аутентификацию на "слабых" каналах управления.
4. Перечень Chart_B участвует в формировании hello-сообщения BAUTH. Таким образом организуется подтверждение совпадения перечня КП (согласован с владельцем) и перечня СИ (получен от КП по "слабому" каналу).

OIDC действительно содержит требование по "позднему согласию" (https://openid.net/specs/openid-connect-core-1_0.html#Consent, https://openid.net/specs/openid-connect-core-1_0.html#ImplicitConsent):

> Once the End-User is authenticated, the Authorization Server MUST obtain an authorization decision before releasing information to the Relying Party. When permitted by the request parameters used, this MAY be done through an interactive dialogue with the End-User that makes it clear what is being consented to or by establishing consent via conditions for processing the request or other means (for example, via previous administrative consent). Sections 2 and 5.3 describe information release mechanisms.

Не думаю, что перенос согласия на ранний этап идет вразрез с OIDC. Все-таки у нас довольно специфическая конфигурация. "Позднее согласие"  усложнит и замедлит взаимодействие.
