### ISSUE TITLE
Права доступа

### ISSUE THREAD

**Issue by agievich** [bcrypto/btok#9]
Непонятные моменты по правам доступа (п. 6.3, табл. 4, 5):
1. Во всех случаях речь идет о праве доступа к какому-то объекту. За одним исключением: "право доступа по паролю CAN". О чем идет речь? Права доступа остаются в силе, если мы открыли сеанс с терминалом после BPACE[CAN], а не после BPACE[PIN] как обычно?
2. Управление PIN через eSign. Почему? Почему глобальный PIN подчинен eSign, а не более универсальной программе eId?
3. Не понятны права терминала в базовом режиме (таблица 5). В базовом режиме терминала нет.

**Comment by olegotory** [comment]
1. После выполнения BPACE по паролю CAN могут быть выполнены следующие операции:
- инициализация и выполнение протоколов BPACE (повторно) и BAUTH, включая операцию проверки сертификата (при выполнении BAUTH); 
- выбор мастер-файла, прикладной программы, элементарного файла eID;
- проверка дополнительного атрибута;
- обновление данных eID;
- чтение данных eID.
Доступ по паролю CAN необходим в случае, когда авторизованному терминалу требуется проверить дополнительный атрибут или прочитать/обновить данные приложения eID без знания пароля PIN, например, обновить данные на id-карте без участия владельца (без знания PIN) может потребоваться в госорганах при изменении места жительства (прописки).
Право доступа по паролю CAN может быть проверено фактически только при проверке сертификата, в котором это право задается. При описании операции провки сертфиката сказано: "Если аутентификация по протоколу BPACE выполнялась с паролем CAN, то в сертификате терминала должно быть установлено право доступа по паролю CAN". Для остальных операций, которые могут выполняться после выполнения BPACE по паролю CAN сказано: "Команда требует предварительной аутентификации по протоколу BPACE c паролем CAN ... ". 
Фактически право доступа по паролю CAN относится только к eID и нужно для следующих операций:
- проверка дополнительного атрибута;
- обновление данных eID;
- чтение данных eID.

2. Управление PIN может выполняться как через eSign, так и через eID. В базовом режиме (без аутентификации терминала) управление PIN может выполняться только через eSign, так как работа с приложением eID требует аутентификации терминала.  В базовом режиме управление PIN выполняется только с использованием клиентской программы (КП), что может быть удобно для пользователя.

3. Таблица 5 определяет права доступа как в базовом, так и в усиленном режиме. В базовом режиме данные права определяются только значением, задаваемым при выполнении BPACE, в усиленном --- дополнительно значением, заданным в сертификате терминала. Считаю логичным, что в базовом режиме пользователь при вводе PIN также дает разрешения, какие операции могут выполняться. Понятно, что КП может подменить разрешения, но это все равно дает дополнительные гарантии, что операции, на которые пользователь не давал разрешения, не будут выполняться. Например, пользователь может заранее и не знать, какие операции будут выполняться КП, некоторые операции для пользователя могут быть неявными (как подпись при формировании запроса на выпуск сертификата).
